/**
 * Edge fingerprint classifier — ported wafw00f + cdncheck signature corpus.
 *
 * Data lives in `src/lib/data/edgeSignatureData.mjs` (generated by
 * `scripts/generate-edge-signatures.mjs` from upstream wafw00f plugin signatures and
 * cdncheck address ranges; attribution in `docs/attribution/edge-fingerprint-sources.md`).
 *
 * Safety model (must hold for every caller):
 *   - `passive` signatures are decidable from one ordinary GET response and are evaluated
 *     against any bounded response snapshot.
 *   - `block_page` signatures describe what a WAF returns when it rejects a request.
 *     They are evaluated ONLY against block evidence an authorized bounded check already
 *     captured (`block_response: true`). Nothing in this module sends traffic or
 *     manufactures attack payloads to produce that evidence.
 *   - Address/CNAME classification is metadata-only: IP family + CIDR membership and
 *     CNAME suffix matching. No DNS lookups, no HTTP requests.
 */

import { isIP } from 'node:net';
import { CVE_SAFE_VALIDATION_CHECK_ID } from '../contracts/cvePipeline.mjs';
import {
  WAF_VENDOR_SIGNATURES,
  CDN_ADDRESS_RANGES,
  WAF_ADDRESS_RANGES,
  EDGE_CNAME_SUFFIXES,
  EDGE_CORPUS_STATS,
} from './data/edgeSignatureData.mjs';

export { EDGE_CORPUS_STATS };

/** Bumped whenever the generated corpus is regenerated from new upstream data. */
export const EDGE_SIGNATURE_CORPUS_VERSION = '1';

const FINGERPRINT_HEADER_VALUE_MAX_LENGTH = 128;
const FINGERPRINT_BODY_MAX_LENGTH = 8192;

const SINGLE_SIGNAL_CONFIDENCE = 0.45;
const EXTRA_SIGNAL_CONFIDENCE = 0.2;
const MAX_VENDOR_CONFIDENCE = 0.95;

function compilePattern(pattern) {
  try {
    return new RegExp(pattern, 'i');
  } catch {
    return null;
  }
}

function compileHeaderName(nameOrPattern) {
  // Corpus header names are lowercase literals; a handful of upstream plugins match
  // case-obfuscated names, which arrive as regex character classes.
  if (/^[a-z0-9-]+$/.test(nameOrPattern)) return { exact: nameOrPattern };
  try {
    return { regex: new RegExp(`^${nameOrPattern}$`, 'i') };
  } catch {
    return null;
  }
}

/** Lazy-compiled vendor signature tables. Rebuilt only if the corpus module is reloaded. */
let compiledVendors = null;

function getCompiledVendors() {
  if (compiledVendors) return compiledVendors;
  const vendors = {};
  const headerNameAllowlist = new Set();
  for (const [vendorKey, vendor] of Object.entries(WAF_VENDOR_SIGNATURES)) {
    const signatures = [];
    for (const sig of vendor.signatures ?? []) {
      if (sig.signal === 'header') {
        const name = compileHeaderName(String(sig.header ?? ''));
        const pattern = compilePattern(String(sig.pattern ?? ''));
        if (!name || !pattern) continue;
        if (name.exact) headerNameAllowlist.add(name.exact);
        signatures.push({ ...sig, compiledHeader: name, compiledPattern: pattern });
        continue;
      }
      if (sig.signal === 'cookie') {
        const pattern = compilePattern(String(sig.pattern ?? ''));
        if (!pattern) continue;
        signatures.push({ ...sig, compiledPattern: pattern });
        continue;
      }
      if (sig.signal === 'content') {
        const pattern = compilePattern(String(sig.pattern ?? ''));
        if (!pattern) continue;
        signatures.push({ ...sig, compiledPattern: pattern });
        continue;
      }
      // status / reason are literal comparisons; keep as-is.
      signatures.push({ ...sig });
    }
    if (signatures.length > 0) vendors[vendorKey] = { name: vendor.name, signatures };
  }
  compiledVendors = Object.freeze({
    vendors: Object.freeze(vendors),
    headerNameAllowlist: Object.freeze(headerNameAllowlist),
  });
  return compiledVendors;
}

/**
 * Bounded, allowlisted header extraction for fingerprinting. Only response header names
 * the corpus actually matches are captured, values truncated. Cookie values are never
 * read — only names.
 * @param {{ headers?: { get?: (name: string) => string | null | undefined } }} [response]
 */
export function extractFingerprintHeaderEntries(response) {
  const { headerNameAllowlist } = getCompiledVendors();
  const headers = response?.headers;
  if (!headers || typeof headers.get !== 'function') return [];
  const entries = [];
  for (const name of headerNameAllowlist) {
    let value;
    try {
      // Call as a method — native Headers.get is receiver-bound; extracting the
      // function reference would lose `this` and throw on every real response.
      value = headers.get(name);
    } catch {
      value = null;
    }
    if (value === null || value === undefined) continue;
    const text = String(value).slice(0, FINGERPRINT_HEADER_VALUE_MAX_LENGTH);
    if (!text) continue;
    entries.push({ name, value: text });
  }
  return entries.sort((a, b) => a.name.localeCompare(b.name));
}

function headerEntriesMatch(headerEntries, compiledHeader, pattern) {
  for (const entry of headerEntries) {
    const nameMatches = compiledHeader.exact
      ? entry.name === compiledHeader.exact
      : compiledHeader.regex.test(entry.name);
    if (nameMatches && pattern.test(entry.value)) return true;
  }
  return false;
}

/**
 * Match one vendor's signatures against response evidence.
 * Block-page signals are skipped unless `includeBlockPage` is true.
 */
function matchVendorSignatures(vendor, evidence, includeBlockPage) {
  const matched = [];
  for (const sig of vendor.signatures) {
    const isBlockTier = sig.tier === 'block_page';
    if (isBlockTier && !includeBlockPage) continue;
    if (sig.signal === 'header') {
      if (headerEntriesMatch(evidence.headerEntries, sig.compiledHeader, sig.compiledPattern)) {
        matched.push({ signal: 'header', header: sig.header, tier: sig.tier });
      }
      continue;
    }
    if (sig.signal === 'cookie') {
      if (evidence.cookieNames.some((name) => sig.compiledPattern.test(name))) {
        matched.push({ signal: 'cookie', tier: sig.tier });
      }
      continue;
    }
    if (sig.signal === 'content') {
      if (evidence.bodyText && sig.compiledPattern.test(evidence.bodyText)) {
        matched.push({ signal: 'content', tier: sig.tier });
      }
      continue;
    }
    if (sig.signal === 'status') {
      if (evidence.statusCode === sig.status) {
        matched.push({ signal: 'status', status: sig.status, tier: sig.tier });
      }
      continue;
    }
    if (sig.signal === 'reason') {
      const reason = evidence.statusReason ?? '';
      if (reason && reason.toLowerCase().includes(String(sig.value).toLowerCase())) {
        matched.push({ signal: 'reason', value: sig.value, tier: sig.tier });
      }
    }
  }
  return matched;
}

function vendorConfidence(matchedSignals) {
  if (matchedSignals.length === 0) return 0;
  const blockSignals = matchedSignals.filter((s) => s.tier === 'block_page').length;
  const passiveSignals = matchedSignals.length - blockSignals;
  const raw = (passiveSignals > 0 ? SINGLE_SIGNAL_CONFIDENCE : 0)
    + Math.max(0, passiveSignals - 1) * EXTRA_SIGNAL_CONFIDENCE
    + blockSignals * EXTRA_SIGNAL_CONFIDENCE;
  return Math.min(MAX_VENDOR_CONFIDENCE, Number(raw.toFixed(3)));
}

/**
 * Rank wafw00f-corpus vendors against one response evidence object.
 * @param {{
 *   headerEntries?: { name: string, value: string }[],
 *   cookieNames?: string[],
 *   bodyText?: string,
 *   statusCode?: number,
 *   statusReason?: string,
 *   blockResponse?: boolean,
 * }} evidence
 * @returns {{ matches: object[], best: object|null, conflicting_vendor_signals: boolean }}
 */
export function classifyWafVendorsFromResponseEvidence(evidence = {}) {
  const { vendors } = getCompiledVendors();
  const normalized = {
    headerEntries: (evidence.headerEntries ?? []).map((e) => ({
      name: String(e.name ?? '').toLowerCase(),
      value: String(e.value ?? '').slice(0, FINGERPRINT_HEADER_VALUE_MAX_LENGTH),
    })),
    cookieNames: (evidence.cookieNames ?? []).map((n) => String(n).toLowerCase()),
    bodyText: evidence.bodyText ? String(evidence.bodyText).slice(0, FINGERPRINT_BODY_MAX_LENGTH) : '',
    statusCode: Number.isInteger(evidence.statusCode) ? evidence.statusCode : null,
    statusReason: evidence.statusReason ?? '',
    blockResponse: evidence.blockResponse === true,
  };

  const matches = [];
  for (const [vendorKey, vendor] of Object.entries(vendors)) {
    const matchedSignals = matchVendorSignatures(vendor, normalized, normalized.blockResponse);
    if (matchedSignals.length === 0) continue;
    matches.push({
      vendor: vendorKey,
      name: vendor.name,
      confidence: vendorConfidence(matchedSignals),
      matched_signals: matchedSignals,
      corpus: 'wafw00f',
    });
  }
  matches.sort((a, b) => b.confidence - a.confidence || a.vendor.localeCompare(b.vendor));

  let conflicting = false;
  if (matches.length >= 2) {
    const rival = matches.find((m) => m.vendor !== matches[0].vendor);
    if (rival && matches[0].confidence - rival.confidence <= 0.2) conflicting = true;
  }
  return { matches, best: matches[0] ?? null, conflicting_vendor_signals: conflicting };
}

// ---------------------------------------------------------------------------
// Address (CIDR) classification — cdncheck port
// ---------------------------------------------------------------------------

function ipToBigint(ip) {
  if (isIP(ip) === 4) {
    const parts = ip.split('.').map(Number);
    return (BigInt(parts[0]) << 24n) | (BigInt(parts[1]) << 16n)
      | (BigInt(parts[2]) << 8n) | BigInt(parts[3]);
  }
  if (isIP(ip) !== 6) return null;
  const doubleColonSplit = ip.split('::');
  let head = doubleColonSplit[0].split(':').filter(Boolean);
  let tail = doubleColonSplit.length > 1 ? doubleColonSplit[1].split(':').filter(Boolean) : [];
  if (doubleColonSplit.length > 1) {
    const missing = 8 - head.length - tail.length;
    if (missing < 0) return null;
    head = [...head, ...Array(missing).fill('0'), ...tail];
    tail = [];
  }
  if (head.length !== 8) return null;
  let value = 0n;
  for (const group of head) {
    const parsed = Number.parseInt(group, 16);
    if (Number.isNaN(parsed) || group.length > 4) return null;
    value = (value << 16n) | BigInt(parsed);
  }
  return value;
}

function cidrToIntervals(cidr) {
  const [range, prefixRaw] = String(cidr).split('/');
  const isV6 = range.includes(':');
  const prefix = Number(prefixRaw ?? (isV6 ? 128 : 32));
  const value = ipToBigint(range);
  if (value === null) return null;
  const bits = isV6 ? 128 : 32;
  if (!Number.isInteger(prefix) || prefix < 0 || prefix > bits) return null;
  const hostBits = BigInt(bits - prefix);
  const size = 1n << hostBits;
  const base = (value >> hostBits) << hostBits;
  return { start: base, end: base + size - 1n };
}

const addressIndexCache = new Map();

function buildAddressIndex(group) {
  const rows = { v4: [], v6: [] };
  for (const [provider, ranges] of Object.entries(group ?? {})) {
    for (const cidr of ranges ?? []) {
      if (String(cidr).includes(':')) continue;
      const interval = cidrToIntervals(cidr);
      if (!interval) continue;
      // v4 and v6 numeric spaces are kept in separate sorted arrays so a v6
      // range can never alias a v4 value.
      rows.v4.push({ ...interval, provider });
    }
  }
  for (const [provider, ranges] of Object.entries(group ?? {})) {
    for (const cidr of ranges ?? []) {
      if (!String(cidr).includes(':')) continue;
      const interval = cidrToIntervals(cidr);
      if (!interval) continue;
      rows.v6.push({ ...interval, provider });
    }
  }
  const pack = (list) => {
    list.sort((a, b) => (a.start < b.start ? -1 : a.start > b.start ? 1 : a.end < b.end ? -1 : 1));
    const maxSpan = list.reduce((max, row) => (row.end - row.start > max ? row.end - row.start : max), 0n);
    return { rows: list, starts: list.map((row) => row.start), maxSpan };
  };
  return { v4: pack(rows.v4), v6: pack(rows.v6) };
}

function getAddressIndex(family) {
  const cached = addressIndexCache.get(family);
  if (cached) return cached;
  const group = family === 'cdn' ? CDN_ADDRESS_RANGES : WAF_ADDRESS_RANGES;
  const index = buildAddressIndex(group);
  addressIndexCache.set(family, Object.freeze(index));
  return index;
}

function lookupAddress(family, ip) {
  const value = ipToBigint(ip);
  if (value === null) return [];
  const version = isIP(ip) === 4 ? 'v4' : 'v6';
  const { rows, starts, maxSpan } = getAddressIndex(family)[version];
  if (rows.length === 0) return [];
  // Rightmost interval whose start <= value, then walk back over potentially
  // overlapping larger intervals.
  let lo = 0;
  let hi = starts.length - 1;
  let idx = -1;
  while (lo <= hi) {
    const mid = (lo + hi) >> 1;
    if (starts[mid] <= value) {
      idx = mid;
      lo = mid + 1;
    } else {
      hi = mid - 1;
    }
  }
  const hits = [];
  const floor = value - maxSpan;
  for (let i = idx; i >= 0; i -= 1) {
    const row = rows[i];
    if (row.end < floor) break;
    if (value >= row.start && value <= row.end
      && !hits.some((h) => h.provider === row.provider)) {
      hits.push({ family, provider: row.provider });
    }
  }
  return hits;
}

/**
 * Metadata-only address classification for resolved edge/origin IPs.
 * @param {string | string[]} ips
 * @returns {{ family: 'cdn'|'waf', provider: string }[]}
 */
export function classifyEdgeByAddress(ips) {
  const list = Array.isArray(ips) ? ips : [ips];
  const hits = [];
  for (const ip of list) {
    const value = String(ip ?? '').trim();
    if (!value) continue;
    hits.push(...lookupAddress('cdn', value));
    hits.push(...lookupAddress('waf', value));
  }
  const seen = new Set();
  return hits.filter((hit) => {
    const key = `${hit.family}:${hit.provider}`;
    if (seen.has(key)) return false;
    seen.add(key);
    return true;
  });
}

/**
 * Metadata-only CNAME suffix classification (cdncheck `common` suffixes).
 * @param {string | string[]} cnames
 */
export function classifyEdgeByCnameChain(cnames) {
  const list = Array.isArray(cnames) ? cnames : [cnames];
  const hits = [];
  const seen = new Set();
  for (const raw of list) {
    const host = String(raw ?? '').trim().toLowerCase().replace(/\.$/, '');
    if (!host || isIP(host)) continue;
    for (const [provider, suffixes] of Object.entries(EDGE_CNAME_SUFFIXES)) {
      for (const suffix of suffixes ?? []) {
        const sfx = String(suffix).toLowerCase();
        if (host === sfx || host.endsWith(`.${sfx}`)) {
          const key = `${provider}:${sfx}`;
          if (!seen.has(key)) {
            seen.add(key);
            hits.push({ provider, suffix: sfx });
          }
        }
      }
    }
  }
  return hits;
}

// ---------------------------------------------------------------------------
// Combined classification
// ---------------------------------------------------------------------------

/**
 * Combined edge fingerprint from bounded response + DNS metadata.
 * Safe to call on any captured snapshot: block-page tier requires `blockResponse`.
 * @param {{
 *   headerEntries?: { name: string, value: string }[],
 *   cookieNames?: string[],
 *   bodyText?: string,
 *   statusCode?: number,
 *   statusReason?: string,
 *   blockResponse?: boolean,
 *   resolvedIps?: (string|null)[],
 *   cnameChain?: (string|null)[],
 * }} input
 */
export function classifyEdgeFingerprint(input = {}) {
  const vendorResult = classifyWafVendorsFromResponseEvidence(input);
  const addressMatches = classifyEdgeByAddress((input.resolvedIps ?? []).filter(Boolean));
  const cnameMatches = classifyEdgeByCnameChain((input.cnameChain ?? []).filter(Boolean));

  const cdnDetected = addressMatches.some((m) => m.family === 'cdn')
    || cnameMatches.some((m) => isCdnCnameProvider(m.provider));
  // Strict corpus semantics: only a vendor signature match or a WAF address-range
  // membership counts. A generic block page without a vendor signal is the scanner's
  // `generic_waf_detected`, not a corpus classification.
  const wafPresent = Boolean(vendorResult.best)
    || addressMatches.some((m) => m.family === 'waf');

  return {
    corpus_version: EDGE_SIGNATURE_CORPUS_VERSION,
    metadata_only: true,
    waf_present: wafPresent,
    cdn_detected: cdnDetected,
    vendor_matches: vendorResult.matches,
    best_vendor: vendorResult.best,
    conflicting_vendor_signals: vendorResult.conflicting_vendor_signals,
    address_matches: addressMatches,
    cname_matches: cnameMatches,
  };
}

const CDN_CNAME_PROVIDERS = new Set(
  Object.keys(CDN_ADDRESS_RANGES).map((p) => p.toLowerCase()),
);

function isCdnCnameProvider(provider) {
  return CDN_CNAME_PROVIDERS.has(String(provider ?? '').toLowerCase());
}

/**
 * Probe-evidence metadata fields for signed WAF fingerprint jobs, mirroring
 * `wafFingerprintProbeEvidenceFields` in `wafProductCatalog.mjs`.
 * @param {string | null | undefined} checkId
 */
export function edgeSignatureProbeEvidenceFields(checkId) {
  if (checkId !== CVE_SAFE_VALIDATION_CHECK_ID) return {};
  return {
    edge_signature_corpus_version: EDGE_SIGNATURE_CORPUS_VERSION,
    edge_signature_waf_vendors: EDGE_CORPUS_STATS.waf_vendors,
    edge_signature_cdn_ranges: EDGE_CORPUS_STATS.cdn_ranges,
    edge_signature_waf_ranges: EDGE_CORPUS_STATS.waf_ranges,
  };
}
