/**
 * Outside-in WAF scanner — bounded metadata-only edge validation.
 * Detects WAF presence, fingerprints vendor/product, validates benign class markers
 * (including safe evasion variants), content-type confusion, optional origin bypass,
 * and emits a posture summary. Outside-in only (ADR-0008): "protected" is derived from
 * external evidence — a signature-backed edge block plus a declared direct-origin lockdown
 * response over a healthy baseline — never from bare status codes, silence, transport errors,
 * or an internal agent.
 */

import { createHash } from 'node:crypto';
import { resolve4, resolve6, resolveCname } from 'node:dns/promises';
import tls from 'node:tls';
import { classifyWafPosture } from '../contracts/wafPosture.mjs';
import { classifyWafProductFromSignals } from './wafProductCatalog.mjs';
import { pinnedFetch } from './pinnedHttpRequest.mjs';
import {
  EDGE_SIGNATURE_CORPUS_VERSION,
  FINGERPRINT_BODY_MAX_LENGTH,
  classifyEdgeFingerprint,
  extractFingerprintHeaderEntries,
} from './edgeFingerprint.mjs';
import { assessWafEffectiveness } from './edgeDetectionProjection.mjs';
import {
  baselineHealth,
  classifyDirectOriginObservation,
  directOriginStatusFor,
  matchControlDenialSignature,
} from './externalObservationOutcomes.mjs';

const MAX_BODY_READ_BYTES = 8192;
const FINGERPRINT_BODY_READ_BYTES = FINGERPRINT_BODY_MAX_LENGTH;
const CHALLENGE_HEADERS = ['cf-mitigated', 'x-waf-block', 'x-bot-challenge', 'x-sucuri-block'];
const SIGNATURE_CHALLENGE_HEADERS = Object.freeze({
  'cf-mitigated': 'cloudflare',
  'x-waf-block': null,
  'x-bot-challenge': null,
  'x-sucuri-block': 'sucuri',
});
const CLASS_MARKER_FAMILIES = Object.freeze({
  sqli: 'sqli_marker',
  xss: 'xss_marker',
  path_traversal: 'path_traversal_marker',
});

export const BENIGN_CLASS_MARKERS = Object.freeze({
  xss: '<astranull-xss-probe/>',
  sqli: "astranull' OR '1'='0",
  path_traversal: '../../astranull-probe',
});

/** Safe evasion-class variants — single-request probes, not reusable attack tooling. */
export const EVASION_VARIANT_MARKERS = Object.freeze({
  sqli_encoded: encodeURIComponent(encodeURIComponent(BENIGN_CLASS_MARKERS.sqli)),
  sqli_case: "AsTrAnUlL' oR '1'='0",
  sqli_comment: "astranull' O/**/R '1'='0",
  xss_encoded: encodeURIComponent(BENIGN_CLASS_MARKERS.xss),
  path_encoded: encodeURIComponent(BENIGN_CLASS_MARKERS.path_traversal),
});

export const OUTSIDE_IN_SCAN_PHASES = Object.freeze([
  'baseline',
  'combined_marker',
  'path_traversal_marker',
  'sqli_marker',
  'xss_marker',
  'sqli_encoded_marker',
  'sqli_case_marker',
  'sqli_comment_marker',
  'xss_encoded_marker',
  'no_user_agent',
  'content_type_confusion',
  'multipart_confusion',
  'origin_bypass',
]);

export const OUTSIDE_IN_SCAN_DEFAULT_BUDGET = 13;

const OUTSIDE_IN_PHASE_RETENTION_PRIORITY = Object.freeze([
  'baseline',
  'path_traversal_marker',
  'sqli_marker',
  'xss_marker',
  'combined_marker',
  'origin_bypass',
  'content_type_confusion',
  'multipart_confusion',
  'sqli_case_marker',
  'sqli_comment_marker',
  'sqli_encoded_marker',
  'xss_encoded_marker',
  'no_user_agent',
]);

const DEFAULT_BROWSER_HEADERS = Object.freeze({
  Accept: 'text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8',
  'User-Agent': 'Mozilla/5.0 (compatible; AstraNullOutsideIn/1.0; +https://astranull.invalid/probe)',
  'Accept-Language': 'en-US,en;q=0.5',
  DNT: '1',
});

// Block-page signatures run against ordinary page bodies (including the baseline homepage), so
// every pattern must be a vendor-specific phrase or a word-bounded product name. Bare substrings
// such as /f5/ (matches hex colours like #f5f5f5), /azure/, /prisma/ or "security policy"
// (every site footer) turned normal pages into "block pages" and made all markers inconclusive.
const BLOCK_PAGE_SIGNATURE_RULES = Object.freeze([
  { id: 'block_sig_cloudflare_generic_v1', pattern: /cloudflare ray id|attention required! \| cloudflare|\bcf-error-details\b|\bcf-ray\b|cdn-cgi\/challenge-platform/i },
  { id: 'block_sig_akamai_generic_v1', pattern: /reference\s*#\d+\.[0-9a-f]+\.\d+\.[0-9a-f]+|\bakamaighost\b/i },
  { id: 'block_sig_incapsula_generic_v1', pattern: /incapsula incident id|_incapsula_resource|\bvisid_incap_|powered by imperva/i },
  { id: 'block_sig_aws_waf_v1', pattern: /\baws ?waf\b|request blocked\.\s*we can't connect to the server for this app|generated by cloudfront \(cloudfront\)/i },
  { id: 'block_sig_modsecurity_v1', pattern: /\bmod_?security\b|this error was generated by mod_security/i },
  { id: 'block_sig_sucuri_v1', pattern: /sucuri website firewall|cloudproxy@sucuri\.net|\bsucuri\/cloudproxy\b/i },
  { id: 'block_sig_f5_asm_v1', pattern: /the requested url was rejected\.? please consult with your administrator|your support id is:?\s*\d+/i },
  { id: 'block_sig_barracuda_v1', pattern: /barracuda (?:networks|web application firewall)|\bbarra_counter_session\b/i },
  { id: 'block_sig_fortiweb_v1', pattern: /\bfortiweb\b|\bfortigate\b/i },
  { id: 'block_sig_azure_waf_v1', pattern: /\bazure front door\b|\bazure application gateway\b|\bx-azure-ref\b|microsoft-azure-application-gateway/i },
  { id: 'block_sig_fastly_v1', pattern: /fastly error: unknown domain|\bfastly-ssl\b/i },
  { id: 'block_sig_radware_v1', pattern: /\bappwall\b|radware (?:security|appwall|cloud waf)/i },
  { id: 'block_sig_paloalto_v1', pattern: /web page blocked[\s\S]{0,300}palo alto networks|palo alto networks[\s\S]{0,300}\b(?:blocked|denied)\b/i },
  { id: 'block_sig_generic_waf_v1', pattern: /\baccess denied\b|\brequest rejected\b|blocked by (?:the |a )?web application firewall|\bweb application firewall\b[\s\S]{0,120}\bblocked\b/i },
  { id: 'block_sig_alertlogic_v1', pattern: /\balert ?logic\b|reference id[\s\S]{0,80}cannot be found/i },
  { id: 'block_sig_zscaler_v1', pattern: /\bzscaler\b|zscloud\.net|accenture policy/i },
  { id: 'block_sig_vercel_v1', pattern: /vercel security checkpoint|\/vercel\/security\//i },
  { id: 'block_sig_zenedge_v1', pattern: /\bzenedge\b|x-zen-fury/i },
  { id: 'block_sig_wordfence_v1', pattern: /\bwordfence\b|\bwf-waf\b/i },
  { id: 'block_sig_ddosguard_v1', pattern: /\bddos-guard\b|\b__ddg\d?_/i },
  { id: 'block_sig_airlock_v1', pattern: /\bairlock\b|\bal[_-]sess\b/i },
  { id: 'block_sig_azion_v1', pattern: /\bazion\b|x-azion-/i },
  { id: 'block_sig_qrator_v1', pattern: /\bqrator\b/i },
  { id: 'block_sig_cloudbric_v1', pattern: /\bcloudbric\b/i },
  { id: 'block_sig_safedog_v1', pattern: /\bsafedog\b/i },
  { id: 'block_sig_yundun_v1', pattern: /\byundun\b/i },
  { id: 'block_sig_imunify360_v1', pattern: /\bimunify360\b/i },
  { id: 'block_sig_link11_v1', pattern: /rhino-core-shield|\blink11\b/i },
  { id: 'block_sig_nexusguard_v1', pattern: /\bnexusguard\b/i },
  { id: 'block_sig_dotdefender_v1', pattern: /\bdotdefender\b/i },
  { id: 'block_sig_webseal_v1', pattern: /\bwebseal\b|ibm security access manager/i },
  { id: 'block_sig_denyall_v1', pattern: /\bdenyall\b|\bda_session\b/i },
  { id: 'block_sig_sitelock_v1', pattern: /\bsitelock\b|\btrueshield\b/i },
  { id: 'block_sig_distil_v1', pattern: /distil networks|distil_r_blocked/i },
  { id: 'block_sig_godaddy_v1', pattern: /godaddy website firewall|godaddy[\s\S]{0,80}\bwaf\b/i },
  { id: 'block_sig_malcare_v1', pattern: /\bmalcare\b|\bblogvault\b/i },
  { id: 'block_sig_webarx_v1', pattern: /\bwebarx\b|\bpatchstack\b/i },
  { id: 'block_sig_naxsi_v1', pattern: /\bnaxsi\b/i },
  { id: 'block_sig_arvancloud_v1', pattern: /\barvancloud\b/i },
  { id: 'block_sig_baidu_v1', pattern: /\byunjiasu\b|baidu[\s\S]{0,40}\bwaf\b/i },
  { id: 'block_sig_chuangyu_v1', pattern: /\bchuangyu\b|365cyd/i },
  { id: 'block_sig_knownsec_v1', pattern: /\bknownsec\b|\bks-waf\b/i },
  { id: 'block_sig_jiasule_v1', pattern: /\bjiasule\b/i },
  { id: 'block_sig_anquanbao_v1', pattern: /\banquanbao\b/i },
  { id: 'block_sig_safeline_v1', pattern: /\bsafeline\b|\bchaitin\b/i },
  { id: 'block_sig_ptaf_v1', pattern: /\bptaf\b|positive technologies/i },
  { id: 'block_sig_variti_v1', pattern: /\bvariti\b/i },
  { id: 'block_sig_transip_v1', pattern: /transip[\s\S]{0,40}\bwaf\b|\bwebshield\b/i },
]);

const REDIRECT_STATUSES = new Set([301, 302, 303, 307, 308]);
const LOW_SPECIFICITY_BLOCK_PAGE_SIGNATURES = new Set(['block_sig_generic_waf_v1']);
// Superseded by the stricter shared vendor markers in externalObservationOutcomes (G2); kept for vendor hints only.
const NON_DENIAL_BLOCK_PAGE_SIGNATURES = new Set([
  'block_sig_generic_waf_v1',
  'block_sig_cloudflare_generic_v1',
  'block_sig_akamai_generic_v1',
  'block_sig_incapsula_generic_v1',
  'block_sig_aws_waf_v1',
]);
const MAX_BASELINE_REDIRECT_HOPS = 2;

let markerParamSequence = 0;

function randomParamName() {
  markerParamSequence = (markerParamSequence + 1) % Number.MAX_SAFE_INTEGER;
  return `p${markerParamSequence.toString(36)}`;
}

function hashBodySnippet(text) {
  const snippet = String(text ?? '').slice(0, MAX_BODY_READ_BYTES);
  if (!snippet) return null;
  return createHash('sha256').update(snippet).digest('hex').slice(0, 32);
}

function headerNamesFromResponse(res) {
  if (!res?.headers) return [];
  const names = [];
  if (typeof res.headers.forEach === 'function') {
    res.headers.forEach((_value, name) => names.push(String(name).toLowerCase()));
    return [...new Set(names)].sort();
  }
  if (typeof res.headers === 'object') {
    return [...new Set(Object.keys(res.headers).map((k) => String(k).toLowerCase()))].sort();
  }
  return [];
}

function headerValue(res, name) {
  if (!res?.headers?.get) return null;
  return res.headers.get(name);
}

function cookieNamesFromResponse(res) {
  const raw = headerValue(res, 'set-cookie');
  if (!raw) return [];
  return [...new Set(
    String(raw)
      .split(/,(?=[^;]+?=)/)
      .map((part) => part.split('=')[0]?.trim())
      .filter(Boolean)
      .map((name) => name.toLowerCase()),
  )].sort();
}

function matchBlockPageSignature(bodyText) {
  const text = String(bodyText ?? '').slice(0, MAX_BODY_READ_BYTES);
  if (!text) return null;
  for (const rule of BLOCK_PAGE_SIGNATURE_RULES) {
    if (rule.pattern.test(text)) return rule.id;
  }
  return null;
}

/**
 * Header values restricted to the fingerprint-corpus allowlist (bounded length) and the
 * raw body text (bounded) are carried on the snapshot for in-memory edge-signature
 * classification only. They are metadata-only inputs and are never returned by the scan
 * result or persisted — result consumers see names, hashes, and classifications.
 */
function dedupeHeaderEntries(entries) {
  const byName = new Map();
  for (const entry of entries) {
    const name = String(entry?.name ?? '').toLowerCase();
    if (!name || byName.has(name)) continue;
    byName.set(name, { name, value: String(entry?.value ?? '') });
  }
  return [...byName.values()].sort((a, b) => a.name.localeCompare(b.name));
}

function fingerprintInputs(res, bodyText) {
  return {
    fingerprint_header_entries: res ? extractFingerprintHeaderEntries(res) : [],
    fingerprint_body_text: String(bodyText ?? '').slice(0, FINGERPRINT_BODY_READ_BYTES),
    fingerprint_status_reason: String(res?.statusText ?? '').slice(0, 256),
  };
}

function wafw00fResponseEvidence(snapshot) {
  if (!snapshot || snapshot.connection_dropped) return null;
  return {
    headerEntries: snapshot.fingerprint_header_entries ?? [],
    cookieNames: snapshot.cookie_names ?? [],
    bodyText: snapshot.fingerprint_body_text ?? '',
    statusCode: snapshot.status_code,
    statusReason: snapshot.fingerprint_status_reason ?? '',
  };
}

const WAFW00F_GENERIC_REASONS = Object.freeze({
  connection_level_blocking: 'Blocking is being done at connection/packet level.',
  server_header_changed: 'The server header is different when an attack is detected.',
  status_code_changed: 'The server returns a different response code when an attack string is used.',
  no_user_agent_response_changed: "The response was different when the request wasn't made from a browser.",
});

/**
 * wafw00f `genericdetect` decision order over snapshots this scanner already captured:
 * no-User-Agent drift, then XSS, path-traversal, and SQLi status drift, then Server header drift
 * on the combined response. Any dropped connection is connection-level blocking.
 */
export function wafw00fGenericDetection({ baseline, noUserAgent, xss, pathTraversal, sqli, combined } = {}) {
  const found = (reasonCode) => ({
    found: true,
    reason_code: reasonCode,
    reason: WAFW00F_GENERIC_REASONS[reasonCode],
  });
  if (!baseline) return { found: false, reason_code: null, reason: null };
  const captured = [baseline, noUserAgent, xss, pathTraversal, sqli, combined].filter(Boolean);
  if (captured.some((snapshot) => snapshot.connection_dropped)) return found('connection_level_blocking');
  if (noUserAgent && noUserAgent.status_code !== baseline.status_code) return found('no_user_agent_response_changed');
  for (const snapshot of [xss, pathTraversal, sqli]) {
    if (snapshot && snapshot.status_code !== baseline.status_code) return found('status_code_changed');
  }
  if (combined && (combined.server_header ?? '') !== (baseline.server_header ?? '')) {
    return found('server_header_changed');
  }
  return { found: false, reason_code: null, reason: null };
}

function responseSnapshot(res, bodyText = '', declaredBlockSignature = null) {
  if (!res) {
    return {
      status_code: 0,
      status_code_class: 'error',
      header_names: [],
      cookie_names: [],
      server_header: null,
      block_page_signature_id: null,
      block_page_fingerprint_hash: null,
      denial_signature: null,
      connection_dropped: true,
      ...fingerprintInputs(null, ''),
    };
  }
  const status = res.status ?? 0;
  const blockPageSignatureId = matchBlockPageSignature(bodyText);
  return {
    status_code: status,
    denial_signature: matchControlDenialSignature({
      statusCode: status,
      headers: res,
      bodyText,
      declared: declaredBlockSignature,
    }),
    status_code_class: status >= 500 ? '5xx' : status >= 400 ? '4xx' : status >= 300 ? '3xx' : '2xx',
    header_names: headerNamesFromResponse(res),
    cookie_names: cookieNamesFromResponse(res),
    server_header: headerValue(res, 'server'),
    block_page_signature_id: blockPageSignatureId,
    block_page_fingerprint_hash: blockPageSignatureId ? hashBodySnippet(bodyText) : null,
    connection_dropped: false,
    ...fingerprintInputs(res, bodyText),
  };
}

function headersWithGet(res) {
  const headers = res?.headers;
  if (!headers || typeof headers.get === 'function') return res;
  const lower = Object.fromEntries(Object.entries(headers).map(([name, value]) => [String(name).toLowerCase(), value]));
  return {
    ...res,
    headers: {
      get: (name) => (lower[String(name).toLowerCase()] ?? null),
      forEach: (fn) => Object.entries(lower).forEach(([name, value]) => fn(value, name)),
    },
  };
}

/** Marker-grading snapshot with control-specific signatures from headers and a bounded body prefix. */
export function markerResponseSnapshot(res, bodyText = '', declaredBlockSignature = null) {
  return responseSnapshot(res ? headersWithGet(res) : null, bodyText, declaredBlockSignature);
}

/** Bounded body prefix for signature matching; HEAD responses and readers that fail yield ''. */
export async function readSignatureBody(res, method = 'GET') {
  if (!res || String(method).toUpperCase() === 'HEAD') return '';
  try {
    if (res.body?.getReader) return await readBoundedResponseBody(res, MAX_BODY_READ_BYTES);
    if (typeof res.text === 'function') return String(await res.text()).slice(0, MAX_BODY_READ_BYTES);
  } catch {
    return '';
  }
  return '';
}

function challengeHeaderDelta(snapshot, baseline) {
  const current = new Set(snapshot?.header_names ?? []);
  const previous = new Set(baseline?.header_names ?? []);
  return CHALLENGE_HEADERS.some((name) => current.has(name) && !previous.has(name));
}

function specificBlockPageDelta(snapshot, baseline) {
  const signature = snapshot?.block_page_signature_id;
  return Boolean(
    signature
    && !LOW_SPECIFICITY_BLOCK_PAGE_SIGNATURES.has(signature)
    && signature !== baseline?.block_page_signature_id,
  );
}

function vendorOfBlockPage(signatureId) {
  const match = /^block_sig_([a-z0-9]+)_/.exec(String(signatureId ?? ''));
  return match ? match[1] : null;
}

/** Control-specific signature on a marker response (G2): shared vendor/declared markers, then new vendor block pages or challenge headers. */
export function markerDenialSignature(snapshot, baseline = null) {
  if (!snapshot || snapshot.connection_dropped || snapshot.error_class) return null;
  if (snapshot.denial_signature) return { ...snapshot.denial_signature, challenge: snapshot.denial_signature.id === 'cloudflare_challenge' };
  const current = new Set(snapshot.header_names ?? []);
  const previous = new Set(baseline?.header_names ?? []);
  // cf-mitigated has one valid value ("challenge"); presence counts only when the value was not captured.
  const valuesCaptured = Object.hasOwn(snapshot, 'denial_signature');
  const header = Object.keys(SIGNATURE_CHALLENGE_HEADERS).find((name) => current.has(name) && !previous.has(name)
    && !(valuesCaptured && name === 'cf-mitigated'));
  if (header) return { kind: 'vendor', id: `challenge_header:${header}`, vendor: SIGNATURE_CHALLENGE_HEADERS[header], challenge: true };
  const page = snapshot.block_page_signature_id;
  if (page && !NON_DENIAL_BLOCK_PAGE_SIGNATURES.has(page) && page !== baseline?.block_page_signature_id) {
    return { kind: 'vendor', id: page, vendor: vendorOfBlockPage(page), challenge: false };
  }
  return null;
}

/** Permitted-path baseline for marker grading: 2xx/3xx with no block signature of any kind. */
export function markerBaselineHealth(baseline) {
  const health = baselineHealth(baseline);
  if (health !== 'healthy') return health;
  const blockPage = baseline.block_page_signature_id && !LOW_SPECIFICITY_BLOCK_PAGE_SIGNATURES.has(baseline.block_page_signature_id);
  const challenge = CHALLENGE_HEADERS.some((name) => baseline.header_names?.includes(name));
  return blockPage || challenge ? 'unhealthy' : 'healthy';
}

const UNSIGNED_STATUS_REASONS = Object.freeze({
  401: 'authentication_gate_precedes_inspection',
  407: 'probe_path_error',
  421: 'misdirected_request',
});

/**
 * Benign-marker grading: blocked only with a control-specific signature; 2xx/3xx without one is not blocked;
 * an unsigned 4xx that differs from baseline is only block_suspected; 401/407/421/5xx and drops stay inconclusive.
 */
export function isBlockedOrChallenged(snapshot, baseline = null) {
  const result = (fields) => ({
    blocked: false,
    challenged: false,
    allowed: false,
    inconclusive: false,
    block_suspected: false,
    denial_signature: null,
    reason: null,
    ...fields,
  });
  if (!snapshot || snapshot.connection_dropped || snapshot.error_class) {
    return result({
      inconclusive: true,
      reason: 'rst_or_drop_unattributed',
      ...(snapshot?.error_class ? { error_class: snapshot.error_class } : {}),
    });
  }
  if (markerBaselineHealth(baseline) !== 'healthy') return result({ inconclusive: true, reason: 'baseline_unhealthy' });
  const signature = markerDenialSignature(snapshot, baseline);
  if (signature) {
    const { challenge, ...denial } = signature;
    return result({
      blocked: true,
      challenged: challenge === true,
      denial_signature: denial,
      ...(denial.vendor ? { waf_product_hint: denial.vendor } : {}),
    });
  }
  const status = snapshot.status_code;
  if (UNSIGNED_STATUS_REASONS[status]) return result({ inconclusive: true, reason: UNSIGNED_STATUS_REASONS[status] });
  if (status >= 500) return result({ inconclusive: true, reason: 'error_not_attributable' });
  if (status === baseline.status_code || (status >= 200 && status < 400)) return result({ allowed: true });
  if (status >= 400) return result({ inconclusive: true, block_suspected: true, reason: 'unattributed_denial' });
  return result({ inconclusive: true, reason: 'status_not_classifiable' });
}

export function detectGenericWafPresence({ baseline, attack, noUserAgent } = {}) {
  const reasons = [];
  const evidenceReasons = [];
  if (!baseline || baseline.connection_dropped || baseline.error_class) {
    return {
      detected: false,
      reason: null,
      reasons: ['baseline_inconclusive'],
      inconclusive: true,
    };
  }
  if (attack?.connection_dropped || attack?.error_class) {
    return {
      detected: false,
      reason: null,
      reasons: ['marker_inconclusive'],
      inconclusive: true,
    };
  }
  if (attack && baseline.status_code !== attack.status_code) reasons.push('status_code_drift');
  if (attack && baseline.server_header && attack.server_header
    && baseline.server_header !== attack.server_header) {
    reasons.push('server_header_drift');
  }
  if (noUserAgent && baseline.status_code !== noUserAgent.status_code) reasons.push('no_user_agent_drift');
  if (challengeHeaderDelta(attack, baseline)) evidenceReasons.push('waf_challenge_header');
  if (specificBlockPageDelta(attack, baseline)) evidenceReasons.push('waf_specific_block_page');
  reasons.push(...evidenceReasons);
  return {
    detected: evidenceReasons.length > 0,
    reason: evidenceReasons[0] ?? null,
    reasons,
    inconclusive: false,
  };
}

function evidenceBackedVendorClassification(classification) {
  const candidates = (classification?.candidates ?? []).flatMap((candidate) => {
    const matchedSignals = (candidate.matched_signals ?? [])
      .filter((signal) => signal !== 'customer_vendor_hint');
    if (matchedSignals.length === 0) return [];
    const declarationBoost = candidate.matched_signals?.includes('customer_vendor_hint') ? 0.1 : 0;
    return [{
      ...candidate,
      confidence: Math.max(0, Number((candidate.confidence - declarationBoost).toFixed(3))),
      matched_signals: matchedSignals,
    }];
  }).sort((left, right) => right.confidence - left.confidence);
  const best = candidates[0] ?? null;
  const rival = best ? candidates.find((candidate) => candidate.vendor !== best.vendor) : null;
  return {
    ...classification,
    candidates,
    best,
    conflicting_vendor_signals: Boolean(
      best && rival && best.confidence - rival.confidence <= 0.2,
    ),
  };
}

function recordMarkerResult(markerResults, entry) {
  const existing = markerResults.find((row) => row.family === entry.family && row.variant === entry.variant);
  if (existing) Object.assign(existing, entry);
  else markerResults.push(entry);
}

function detectEvasionBypass(markerResults) {
  const plainFamilies = ['sqli_marker', 'xss_marker', 'path_traversal_marker'];
  const evasionFamilies = [
    'sqli_encoded_marker',
    'sqli_case_marker',
    'sqli_comment_marker',
    'xss_encoded_marker',
    'content_type_confusion',
    'multipart_confusion',
  ];
  const plainRows = markerResults.filter((row) => plainFamilies.includes(row.family));
  const plainBlocked = plainRows.length > 0 && plainRows.every((row) => row.blocked);
  const evasionAllowed = markerResults
    .filter((row) => evasionFamilies.includes(row.family))
    .some((row) => row.allowed);
  return plainBlocked && evasionAllowed;
}

/**
 * @param {object} input
 * @param {boolean} [input.originLockdownConfirmed=false] — declared direct-origin lockdown
 *   signature over a healthy baseline; silence or errors never qualify, so the scan stays "edge_protected".
 * @param {string} [input.domXssValidation='external_only']
 * @param {object|null} [input.edgeSignature=null] — classifyEdgeFingerprint() result.
 */
export function buildOutsideInPostureReport({
  wafDetected = false,
  genericWafDetected = false,
  markerResults = [],
  originBypassConfirmed = false,
  wafRequired = true,
  vendorClassification = null,
  originLockdownConfirmed = false,
  evasionBypassSuspected = false,
  domXssValidation = 'external_only',
  edgeSignature = null,
  coverageComplete,
  probeErrorsPresent = false,
} = {}) {
  const anyMarkerAllowed = markerResults.some((m) => m.allowed === true);
  const markerInconclusive = markerResults.some((marker) => (
    marker.inconclusive === true || Boolean(marker.error_class)
  ));
  const probeInconclusive = probeErrorsPresent || markerInconclusive;
  const classMarkerResults = Object.values(CLASS_MARKER_FAMILIES).map(
    (family) => markerResults.find((row) => row.family === family && row.variant === 'plain'),
  );
  const classCoverageComplete = classMarkerResults.every(Boolean);
  const probeValidationPassed = classCoverageComplete
    && classMarkerResults.every((marker) => marker.blocked === true)
    && !anyMarkerAllowed
    && !probeInconclusive;
  const validationFailed = markerResults.length > 0 && (anyMarkerAllowed || evasionBypassSuspected);

  // Full "protected" additionally requires a declared direct-origin lockdown signature (ADR-0008, ADR-0017).
  const edgeValidationPassed = probeValidationPassed && !evasionBypassSuspected;
  const validationPassed = edgeValidationPassed && originLockdownConfirmed;

  const effectiveWafDetected = wafDetected || genericWafDetected
    || Boolean(vendorClassification?.best)
    || edgeSignature?.waf_present === true;
  const posture = classifyWafPosture({
    wafDetected: effectiveWafDetected,
    validationPassed,
    validationFailed,
    originBypassConfirmed,
    wafRequired,
    // This report is only built after an outside-in probe scan actually executed against the
    // target, so "no WAF detected" here reflects a completed check, not silence.
    coverageGapEvidence: true,
  });

  const reason_codes = [...posture.reason_codes];
  if (evasionBypassSuspected && !reason_codes.includes('scenario_category_failed')) {
    reason_codes.push('scenario_category_failed');
  }
  if (edgeValidationPassed && !originLockdownConfirmed
    && !reason_codes.includes('insufficient_validation_evidence')) {
    reason_codes.push('insufficient_validation_evidence');
  }
  if (probeInconclusive && !validationFailed && !reason_codes.includes('probe_result_inconclusive')) {
    reason_codes.push('probe_result_inconclusive');
  }

  let posture_label = 'Unknown';
  let posture_status = posture.status;

  if (originBypassConfirmed) {
    posture_label = 'Bypass Risk';
    posture_status = 'underprotected';
  } else if (validationFailed) {
    posture_label = 'Underprotected';
    posture_status = 'underprotected';
  } else if (probeInconclusive) {
    posture_label = 'Inconclusive';
    posture_status = 'inconclusive';
  } else if (validationPassed) {
    posture_label = 'Protected';
    posture_status = 'protected';
  } else if (edgeValidationPassed && effectiveWafDetected) {
    posture_label = 'Edge protected · origin lockdown unverified';
    posture_status = 'edge_protected';
  } else if (posture.status === 'unprotected') {
    posture_label = 'Unprotected';
  } else if (posture.status === 'excluded') {
    posture_label = 'Excluded';
  } else if (posture.status === 'underprotected') {
    posture_label = 'Underprotected';
  }

  const best = vendorClassification?.best ?? null;
  const edgeBest = edgeSignature?.best_vendor ?? null;
  const corpusWafPresent = edgeSignature?.waf_present === true;
  const corpusDetected = corpusWafPresent || edgeSignature?.cdn_detected === true;
  const wafConfidence = best?.confidence
    ?? (edgeBest ? Math.max(edgeBest.confidence, genericWafDetected ? 0.45 : 0) : (genericWafDetected ? 0.45 : 0));
  const effectiveness = assessWafEffectiveness({
    wafPresent: effectiveWafDetected,
    markerResults,
    coverageComplete,
    transportError: probeErrorsPresent,
  });
  const class_posture = Object.fromEntries(Object.entries(CLASS_MARKER_FAMILIES).map(([className, family]) => {
    const observation = markerResults.find((row) => row.family === family && row.variant === 'plain');
    const status = observation?.blocked === true
      ? 'protected'
      : observation?.allowed === true
        ? 'underprotected'
        : 'unknown';
    return [className, status];
  }));
  return {
    posture_status,
    posture_label,
    reason_codes: [...new Set(reason_codes)],
    waf_detected: effectiveWafDetected,
    waf_fingerprint_detected: Boolean(best) || wafDetected || genericWafDetected || Boolean(edgeBest),
    generic_waf_detected: genericWafDetected,
    detected_vendor: best?.vendor ?? edgeBest?.vendor ?? null,
    detected_product: best?.product ?? null,
    waf_product_hint: best ? `${best.vendor}/${best.product}` : (edgeBest ? `corpus:${edgeBest.vendor}` : null),
    waf_confidence: wafConfidence,
    cdn_detected: edgeSignature?.cdn_detected === true,
    edge_signature_corpus_version: corpusDetected ? (edgeSignature?.corpus_version ?? null) : null,
    validation_passed: validationPassed,
    validation_failed: validationFailed,
    probe_validation_passed: probeValidationPassed,
    edge_validation_passed: edgeValidationPassed,
    origin_lockdown_confirmed: originLockdownConfirmed,
    evasion_bypass_suspected: evasionBypassSuspected,
    dom_xss_validation: domXssValidation,
    origin_bypass_confirmed: originBypassConfirmed,
    ...(typeof coverageComplete === 'boolean' ? { coverage_complete: coverageComplete } : {}),
    class_posture,
    waf_effectiveness: effectiveness,
    marker_summary: {
      probes_sent: markerResults.length,
      blocked_count: markerResults.filter((m) => m.blocked).length,
      allowed_count: markerResults.filter((m) => m.allowed).length,
      challenged_count: markerResults.filter((m) => m.challenged).length,
      inconclusive_count: markerResults.filter((m) => m.inconclusive || m.error_class).length,
      evasion_probes_sent: markerResults.filter((m) => String(m.variant ?? '') !== 'plain').length,
    },
  };
}

function buildMultipartConfusionBody(marker, boundary = 'astranullBoundary7f3a') {
  const fieldName = randomParamName();
  return [
    `--${boundary}`,
    `Content-Disposition: form-data; name="${fieldName}"`,
    '',
    marker,
    `--${boundary}--`,
    '',
  ].join('\r\n');
}

function buildUrl(baseUrl, { pathSuffix = '', params = {}, rawParams = {} } = {}) {
  const url = new URL(baseUrl);
  if (pathSuffix) {
    const joined = `${url.pathname.replace(/\/$/, '')}/${pathSuffix}`.replace(/\/+/g, '/');
    url.pathname = joined.startsWith('/') ? joined : `/${joined}`;
  }
  for (const [key, value] of Object.entries(params)) {
    url.searchParams.set(key, value);
  }
  let href = url.href;
  for (const [key, value] of Object.entries(rawParams)) {
    const sep = href.includes('?') ? '&' : '?';
    href = `${href}${sep}${key}=${value}`;
  }
  return href;
}

function normalizeDnsHostname(value) {
  return String(value ?? '').trim().toLowerCase().replace(/\.$/, '');
}

/** Bounded CNAME-chain depth. cdncheck suffix matching only needs the edge-facing hops. */
const DNS_CNAME_CHAIN_MAX = 8;
/** Bounded address count per family, keeping the metadata summary small and comparable. */
const DNS_ADDRESSES_PER_FAMILY_MAX = 4;

/**
 * Optional standalone CNAME/A/AAAA lookup chain for metadata-only WAF/CDN catalog matching.
 * This raw collector is direct-helper opt-in only; the signed capability adapter keeps it disabled
 * because these operations are not separately signed, reserved, counted, pinned, and bounded.
 *
 * Returns the display `dns_chain` string plus the structured `cname_chain`/`resolved_ips` the
 * pinned cdncheck corpus consumes. Structured fields avoid re-parsing the display string.
 *
 * @param {string} hostname
 * @param {{
 *   resolveCname?: typeof resolveCname,
 *   resolve4?: typeof resolve4,
 *   resolve6?: typeof resolve6,
 * }} [deps]
 */
export async function resolveOutsideInDnsHints(hostname, deps = {}) {
  const host = normalizeDnsHostname(hostname);
  if (!host) {
    return { dns_chain: null, cname_chain: [], resolved_ips: [], error_class: 'missing_hostname' };
  }

  const resolveCnameFn = deps.resolveCname ?? resolveCname;
  const resolve4Fn = deps.resolve4 ?? resolve4;
  // A caller that injects resolvers is running hermetically. Falling back to the real AAAA
  // resolver for the one function it did not stub would put live DNS behind an injected test.
  const partiallyInjected = Boolean(deps.resolveCname || deps.resolve4);
  const resolve6Fn = deps.resolve6 ?? (partiallyInjected ? async () => [] : resolve6);
  const cnameChain = [host];
  const seen = new Set([host]);
  const resolvedIps = [];

  try {
    // Follow the delegation chain hop by hop. A single hop only reveals the first edge provider;
    // stacked CDN/WAF deployments expose their vendor further down the chain.
    while (cnameChain.length < DNS_CNAME_CHAIN_MAX) {
      let next = null;
      try {
        const cnames = await resolveCnameFn(cnameChain[cnameChain.length - 1]);
        next = normalizeDnsHostname(cnames?.[0]);
      } catch {
        /* ENODATA / ENOTFOUND — chain ends here, proceed to address lookup */
      }
      if (!next || seen.has(next)) break;
      seen.add(next);
      cnameChain.push(next);
    }

    const lookupHost = cnameChain[cnameChain.length - 1];
    const [v4, v6] = await Promise.all([
      resolve4Fn(lookupHost).catch(() => []),
      resolve6Fn(lookupHost).catch(() => []),
    ]);
    for (const list of [v4, v6]) {
      for (const entry of (Array.isArray(list) ? list : []).slice(0, DNS_ADDRESSES_PER_FAMILY_MAX)) {
        const address = String(entry ?? '').trim();
        if (address && !resolvedIps.includes(address)) resolvedIps.push(address);
      }
    }
  } catch (err) {
    return {
      dns_chain: cnameChain.join(' '),
      cname_chain: cnameChain,
      resolved_ips: resolvedIps,
      error_class: err?.code ?? err?.name ?? 'dns_lookup_failed',
    };
  }

  return {
    dns_chain: [...cnameChain, ...resolvedIps].join(' '),
    cname_chain: cnameChain,
    resolved_ips: resolvedIps,
  };
}

/**
 * Optional standalone TLS handshake read (protocol + cipher name only). This raw collector is
 * direct-helper opt-in only; signed outside-in execution keeps it disabled unless a future
 * operation is separately signed, reserved, counted, deadline-bounded, and destination-pinned.
 * @param {string} url
 * @param {{ tlsConnect?: typeof tls.connect, timeoutMs?: number }} [deps]
 */
export async function resolveOutsideInTlsHints(url, deps = {}) {
  let parsed;
  try {
    parsed = new URL(String(url ?? '').trim());
  } catch {
    return { tls_protocol_hint: null, tls_cipher_hint: null, error_class: 'invalid_url' };
  }

  if (parsed.protocol !== 'https:') {
    return { tls_protocol_hint: null, tls_cipher_hint: null };
  }

  const tlsConnectFn = deps.tlsConnect ?? tls.connect;
  const timeoutMs = Number.isInteger(deps.timeoutMs) && deps.timeoutMs > 0 ? deps.timeoutMs : 3000;
  const port = parsed.port ? Number(parsed.port) : 443;
  const host = parsed.hostname;
  const connectHost = deps.connectHost ?? host;

  return new Promise((resolve) => {
    let settled = false;
    const socket = tlsConnectFn({
      host: connectHost,
      port,
      servername: host,
      rejectUnauthorized: false,
    });

    const timer = setTimeout(() => {
      if (settled) return;
      settled = true;
      socket.destroy();
      resolve({
        tls_protocol_hint: null,
        tls_cipher_hint: null,
        error_class: 'tls_timeout',
      });
    }, timeoutMs);

    const finish = (result) => {
      if (settled) return;
      settled = true;
      clearTimeout(timer);
      socket.destroy();
      resolve(result);
    };

    socket.once('secureConnect', () => {
      finish({
        tls_protocol_hint: socket.getProtocol() ?? null,
        tls_cipher_hint: socket.getCipher()?.name ?? null,
      });
    });
    socket.once('error', (err) => {
      finish({
        tls_protocol_hint: null,
        tls_cipher_hint: null,
        error_class: err?.code ?? err?.name ?? 'tls_handshake_failed',
      });
    });
  });
}

function resolveRedirectTarget(location, baseUrl) {
  const raw = String(location ?? '').trim();
  if (!raw) return null;
  try {
    return new URL(raw, baseUrl).href;
  } catch {
    return null;
  }
}

/**
 * Baseline GET with optional manual redirect follow (bounded, baseline only).
 */
async function runBaselineGet(
  url,
  headers,
  { followRedirects = false, timeoutMs, requestBudget = 1, deps, declaredBlockSignature = null } = {},
) {
  let currentUrl = url;
  let redirectHops = 0;
  let requestsSent = 0;
  let finalUrlHostname = null;

  while (requestsSent < requestBudget) {
    requestsSent += 1;
    const { res, bodyText, error } = await boundedRequest(
      currentUrl,
      { method: 'GET', headers, activity_phase: 'baseline' },
      timeoutMs,
      deps,
    );

    try {
      finalUrlHostname = new URL(currentUrl).hostname;
    } catch {
      finalUrlHostname = null;
    }

    if (error || !res) {
      const snapshot = error
        ? { ...responseSnapshot(null), error_class: error.name ?? error.code ?? 'probe_failed' }
        : responseSnapshot(res, bodyText, declaredBlockSignature);
      return {
        snapshot,
        redirect_hops: redirectHops,
        final_url_hostname: finalUrlHostname,
        requests_sent: requestsSent,
      };
    }

    if (followRedirects && REDIRECT_STATUSES.has(res.status)
      && redirectHops < MAX_BASELINE_REDIRECT_HOPS && requestsSent < requestBudget) {
      const nextUrl = resolveRedirectTarget(headerValue(res, 'location'), currentUrl);
      if (nextUrl && nextUrl !== currentUrl) {
        redirectHops += 1;
        currentUrl = nextUrl;
        continue;
      }
    }

    return {
      snapshot: responseSnapshot(res, bodyText, declaredBlockSignature),
      redirect_hops: redirectHops,
      final_url_hostname: finalUrlHostname,
      requests_sent: requestsSent,
    };
  }

  return {
    snapshot: { ...responseSnapshot(null), error_class: 'request_budget_exhausted' },
    redirect_hops: redirectHops,
    final_url_hostname: finalUrlHostname,
    requests_sent: requestsSent,
  };
}

export async function readBoundedResponseBody(res, maxBytes = MAX_BODY_READ_BYTES) {
  const reader = res?.body?.getReader?.();
  if (!reader) return '';

  const chunks = [];
  let total = 0;
  let complete = false;
  try {
    while (total < maxBytes) {
      const { done, value } = await reader.read();
      if (done) {
        complete = true;
        break;
      }
      if (!(value instanceof Uint8Array) || value.byteLength === 0) continue;
      const remaining = maxBytes - total;
      const chunk = value.byteLength <= remaining ? value : value.subarray(0, remaining);
      chunks.push(chunk);
      total += chunk.byteLength;
      if (value.byteLength > remaining) break;
    }
  } finally {
    if (!complete) {
      try {
        await reader.cancel('response_body_limit_reached');
      } catch {
        // The transport may already be closed; the copied evidence remains bounded.
      }
    }
    reader.releaseLock?.();
  }

  const body = new Uint8Array(total);
  let offset = 0;
  for (const chunk of chunks) {
    body.set(chunk, offset);
    offset += chunk.byteLength;
  }
  return new TextDecoder('utf-8', { fatal: false }).decode(body);
}

async function boundedRequest(url, { method = 'GET', headers = {}, body = null, activity_phase }, timeoutMs, deps) {
  const fetchFn = deps.fetchFn ?? ((input, init) => pinnedFetch(input, init, deps));
  const controller = new AbortController();
  const timer = setTimeout(() => controller.abort(), timeoutMs);
  try {
    const res = await fetchFn(url, {
      method,
      headers,
      body,
      redirect: 'manual',
      signal: controller.signal,
      activity_phase,
    });
    if (!res || !Number.isInteger(res.status)) {
      const error = new Error('invalid HTTP response from probe transport');
      error.code = 'invalid_probe_response';
      return { res: null, bodyText: '', error };
    }
    const bodyText = await readBoundedResponseBody(res, FINGERPRINT_BODY_READ_BYTES);
    return { res, bodyText, error: null };
  } catch (err) {
    if (
      err?.code === 'signed_operation_budget_exceeded'
      || err?.code === 'probe_job_deadline_exceeded'
    ) {
      throw err;
    }
    return { res: null, bodyText: '', error: err };
  } finally {
    clearTimeout(timer);
  }
}

/**
 * Priority-ordered scan phases for a given request budget.
 * @param {number} budget
 * @param {{ hasDirectIp?: boolean }} options
 */
export function buildOutsideInScanPlan(budget, { hasDirectIp = false } = {}) {
  const methods = new Map([
    ['content_type_confusion', 'POST'],
    ['multipart_confusion', 'POST'],
    ['origin_bypass', 'HEAD'],
  ]);
  const availablePhases = OUTSIDE_IN_SCAN_PHASES.filter((phase) => hasDirectIp || phase !== 'origin_bypass');
  const boundedBudget = Number.isInteger(budget) && budget > 0 ? budget : 0;
  const retained = new Set(
    OUTSIDE_IN_PHASE_RETENTION_PRIORITY
      .filter((phase) => availablePhases.includes(phase))
      .slice(0, boundedBudget),
  );
  return availablePhases
    .filter((phase) => retained.has(phase))
    .map((phase) => ({ phase, method: methods.get(phase) ?? 'GET' }));
}

/**
 * @param {{
 *   url: string,
 *   hostname?: string,
 *   directIp?: string,
 *   budget?: number,
 *   timeoutMs?: number,
 *   wafRequired?: boolean,
 *   customerVendorHint?: string,
 *   domXssValidation?: string,
 *   followRedirects?: boolean,
 *   collectNetworkHints?: boolean,
 *   fetchFn?: typeof fetch,
 *   resolveCname?: typeof resolveCname,
 *   resolve4?: typeof resolve4,
 *   tlsConnect?: typeof tls.connect,
 *   tlsHost?: string,
 *   originBypassFn?: (args: object) => Promise<{ res: object|null, error: Error|null, bodyText?: string }>,
 *   declaredBlockSignature?: { status_code?: number, body_sha256?: string, header?: { name: string, value?: string } },
 *   declaredOriginLockdown?: { status_code?: number, body_sha256?: string, header?: { name: string, value?: string }, mtls?: boolean },
 * }} options
 */
export async function runOutsideInWafScan(options = {}) {
  const url = String(options.url ?? '').trim();
  if (!url) {
    return { error_class: 'unsupported_target', requests_sent: 0, phases: [] };
  }

  const budget = Number.isInteger(options.budget) && options.budget > 0
    ? options.budget
    : OUTSIDE_IN_SCAN_DEFAULT_BUDGET;
  const timeoutMs = Number.isInteger(options.timeoutMs) && options.timeoutMs > 0 ? options.timeoutMs : 5000;
  const followRedirects = options.followRedirects === true;
  const collectNetworkHints = options.collectNetworkHints === true;
  const deps = {
    fetchFn: options.fetchFn,
    resolveCname: options.resolveCname,
    resolve4: options.resolve4,
    resolve6: options.resolve6,
    tlsConnect: options.tlsConnect,
    tlsHost: options.tlsHost,
  };
  const started = Date.now();
  let requestsSent = 0;
  const phaseLog = [];
  function recordPhase(entry) {
    phaseLog.push(entry);
    try { options.onPhase?.(entry); } catch { /* Observation cannot alter the bounded scan. */ }
  }
  const markerResults = [];
  const transportErrorClasses = [];

  function recordTransportError(snapshot) {
    const errorClass = String(snapshot?.error_class ?? '').trim();
    if (errorClass && !transportErrorClasses.includes(errorClass)) transportErrorClasses.push(errorClass);
  }

  const declaredBlockSignature = options.declaredBlockSignature ?? null;
  const directIp = options.directIp ?? null;
  const hostname = options.hostname ?? (() => {
    try { return new URL(url).hostname; } catch { return null; }
  })();
  const plan = buildOutsideInScanPlan(budget, { hasDirectIp: Boolean(directIp && hostname) });
  const plannedPhases = new Set(plan.map((entry) => entry.phase));
  const phasesPlanned = OUTSIDE_IN_SCAN_PHASES.filter(
    (phase) => Boolean(directIp && hostname) || phase !== 'origin_bypass',
  );
  const phasesDropped = phasesPlanned.filter((phase) => !plannedPhases.has(phase));

  const suppliedIps = Array.isArray(options.resolvedIps)
    ? options.resolvedIps.map((ip) => String(ip ?? '').trim()).filter(Boolean)
    : [];
  const suppliedCnameChain = Array.isArray(options.cnameChain)
    ? options.cnameChain.map((name) => normalizeDnsHostname(name)).filter(Boolean)
    : [];
  const [initialDnsHints, tlsHints] = collectNetworkHints
    ? await Promise.all([
        hostname
          ? resolveOutsideInDnsHints(hostname, deps)
          : Promise.resolve({ dns_chain: null, cname_chain: [], resolved_ips: [] }),
        resolveOutsideInTlsHints(url, {
          tlsConnect: deps.tlsConnect,
          connectHost: deps.tlsHost,
          timeoutMs: Math.min(timeoutMs, 3000),
        }),
      ])
    : [{ dns_chain: null, cname_chain: [], resolved_ips: [] }, {}];

  let redirectHops = 0;
  let finalUrlHostname = null;
  let dnsChainHint = initialDnsHints.dns_chain ?? null;
  const dnsCnameChain = [...new Set([...(initialDnsHints.cname_chain ?? []), ...suppliedCnameChain])];
  const dnsResolvedIps = [...new Set([...(initialDnsHints.resolved_ips ?? []), ...suppliedIps])];
  const dnsObserved = collectNetworkHints || suppliedIps.length > 0 || suppliedCnameChain.length > 0;

  async function runGetPhase(phase, requestUrl, headers) {
    if (requestsSent >= budget) return null;
    requestsSent += 1;
    const { res, bodyText, error } = await boundedRequest(requestUrl, { method: 'GET', headers, activity_phase: phase }, timeoutMs, deps);
    const snapshot = error
      ? { ...responseSnapshot(null), error_class: error.name ?? error.code ?? 'probe_failed' }
      : responseSnapshot(res, bodyText, declaredBlockSignature);
    recordTransportError(snapshot);
    recordPhase({
      phase,
      status_code: snapshot.status_code,
      ...(snapshot.error_class ? { error_class: snapshot.error_class } : {}),
    });
    return snapshot;
  }

  let baseline = null;
  let combined = null;
  let sqli = null;
  let xss = null;
  let pathTraversal = null;
  let noUserAgent = null;

  if (plannedPhases.has('baseline')) {
    if (requestsSent >= budget) {
      return { error_class: 'request_budget_exhausted', requests_sent: requestsSent, phases: phaseLog };
    }
    const baselineResult = await runBaselineGet(url, { ...DEFAULT_BROWSER_HEADERS }, {
      followRedirects,
      timeoutMs,
      requestBudget: budget - requestsSent,
      deps,
      declaredBlockSignature,
    });
    requestsSent += baselineResult.requests_sent;
    baseline = baselineResult.snapshot;
    recordTransportError(baseline);
    redirectHops = baselineResult.redirect_hops;
    finalUrlHostname = baselineResult.final_url_hostname;
    recordPhase({
      phase: 'baseline',
      status_code: baseline.status_code,
      redirect_hops: redirectHops,
      ...(baseline.error_class ? { error_class: baseline.error_class } : {}),
    });

    if (
      followRedirects
      && collectNetworkHints
      && finalUrlHostname
      && finalUrlHostname !== hostname
    ) {
      const finalDnsHints = await resolveOutsideInDnsHints(finalUrlHostname, deps);
      if (finalDnsHints.dns_chain) {
        dnsChainHint = [dnsChainHint, finalDnsHints.dns_chain].filter(Boolean).join(' ');
      }
      for (const cname of finalDnsHints.cname_chain ?? []) {
        if (!dnsCnameChain.includes(cname)) dnsCnameChain.push(cname);
      }
      for (const ip of finalDnsHints.resolved_ips ?? []) {
        if (!dnsResolvedIps.includes(ip)) dnsResolvedIps.push(ip);
      }
    }
  }

  if (plannedPhases.has('combined_marker')) {
    const combinedParams = {
      [randomParamName()]: BENIGN_CLASS_MARKERS.xss,
      [randomParamName()]: BENIGN_CLASS_MARKERS.sqli,
      [randomParamName()]: BENIGN_CLASS_MARKERS.path_traversal,
    };
    combined = await runGetPhase('combined_marker', buildUrl(url, { params: combinedParams }), { ...DEFAULT_BROWSER_HEADERS });
    if (combined) {
      const evalResult = isBlockedOrChallenged(combined, baseline);
      recordMarkerResult(markerResults, {
        family: 'combined_marker',
        variant: 'mixed_classes',
        ...evalResult,
        status_code: combined.status_code,
      });
    }
  }

  if (plannedPhases.has('path_traversal_marker')) {
    pathTraversal = await runGetPhase(
      'path_traversal_marker',
      buildUrl(url, { pathSuffix: BENIGN_CLASS_MARKERS.path_traversal }),
      { ...DEFAULT_BROWSER_HEADERS },
    );
    if (pathTraversal) {
      recordMarkerResult(markerResults, {
        family: 'path_traversal_marker',
        variant: 'plain',
        ...isBlockedOrChallenged(pathTraversal, baseline),
        status_code: pathTraversal.status_code,
      });
    }
  }

  if (plannedPhases.has('sqli_marker')) {
    sqli = await runGetPhase(
      'sqli_marker',
      buildUrl(url, { params: { [randomParamName()]: BENIGN_CLASS_MARKERS.sqli } }),
      { ...DEFAULT_BROWSER_HEADERS },
    );
    if (sqli) {
      recordMarkerResult(markerResults, {
        family: 'sqli_marker',
        variant: 'plain',
        ...isBlockedOrChallenged(sqli, baseline),
        status_code: sqli.status_code,
      });
    }
  }

  if (plannedPhases.has('sqli_encoded_marker')) {
    const snap = await runGetPhase(
      'sqli_encoded_marker',
      buildUrl(url, { rawParams: { [randomParamName()]: EVASION_VARIANT_MARKERS.sqli_encoded } }),
      { ...DEFAULT_BROWSER_HEADERS },
    );
    if (snap) {
      recordMarkerResult(markerResults, {
        family: 'sqli_encoded_marker',
        variant: 'double_url_encoded',
        ...isBlockedOrChallenged(snap, baseline),
        status_code: snap.status_code,
      });
    }
  }

  if (plannedPhases.has('sqli_case_marker')) {
    const snap = await runGetPhase(
      'sqli_case_marker',
      buildUrl(url, { params: { [randomParamName()]: EVASION_VARIANT_MARKERS.sqli_case } }),
      { ...DEFAULT_BROWSER_HEADERS },
    );
    if (snap) {
      recordMarkerResult(markerResults, {
        family: 'sqli_case_marker',
        variant: 'case_mixed',
        ...isBlockedOrChallenged(snap, baseline),
        status_code: snap.status_code,
      });
    }
  }

  if (plannedPhases.has('sqli_comment_marker')) {
    const snap = await runGetPhase(
      'sqli_comment_marker',
      buildUrl(url, { params: { [randomParamName()]: EVASION_VARIANT_MARKERS.sqli_comment } }),
      { ...DEFAULT_BROWSER_HEADERS },
    );
    if (snap) {
      recordMarkerResult(markerResults, {
        family: 'sqli_comment_marker',
        variant: 'comment_insertion',
        ...isBlockedOrChallenged(snap, baseline),
        status_code: snap.status_code,
      });
    }
  }

  if (plannedPhases.has('xss_marker')) {
    xss = await runGetPhase(
      'xss_marker',
      buildUrl(url, { params: { [randomParamName()]: BENIGN_CLASS_MARKERS.xss } }),
      { ...DEFAULT_BROWSER_HEADERS },
    );
    if (xss) {
      recordMarkerResult(markerResults, {
        family: 'xss_marker',
        variant: 'plain',
        ...isBlockedOrChallenged(xss, baseline),
        status_code: xss.status_code,
      });
    }
  }

  if (plannedPhases.has('xss_encoded_marker')) {
    const snap = await runGetPhase(
      'xss_encoded_marker',
      buildUrl(url, { rawParams: { [randomParamName()]: EVASION_VARIANT_MARKERS.xss_encoded } }),
      { ...DEFAULT_BROWSER_HEADERS },
    );
    if (snap) {
      recordMarkerResult(markerResults, {
        family: 'xss_encoded_marker',
        variant: 'url_encoded',
        ...isBlockedOrChallenged(snap, baseline),
        status_code: snap.status_code,
      });
    }
  }

  if (plannedPhases.has('no_user_agent')) {
    const noUaHeaders = { ...DEFAULT_BROWSER_HEADERS };
    delete noUaHeaders['User-Agent'];
    noUserAgent = await runGetPhase('no_user_agent', url, noUaHeaders);
  }

  if (plannedPhases.has('content_type_confusion') && requestsSent < budget) {
    requestsSent += 1;
    const formBody = `${randomParamName()}=${encodeURIComponent(BENIGN_CLASS_MARKERS.sqli)}`;
    const { res, bodyText, error } = await boundedRequest(url, {
      method: 'POST',
      activity_phase: 'content_type_confusion',
      headers: {
        ...DEFAULT_BROWSER_HEADERS,
        'Content-Type': 'application/json',
        'Content-Length': String(formBody.length),
      },
      body: formBody,
    }, timeoutMs, deps);
    const snapshot = error
      ? { ...responseSnapshot(null), error_class: error.name ?? error.code ?? 'probe_failed' }
      : responseSnapshot(res, bodyText, declaredBlockSignature);
    recordTransportError(snapshot);
    recordPhase({
      phase: 'content_type_confusion',
      status_code: snapshot.status_code,
      ...(snapshot.error_class ? { error_class: snapshot.error_class } : {}),
    });
    const contentTypeEval = isBlockedOrChallenged(snapshot, baseline);
    recordMarkerResult(markerResults, {
      family: 'content_type_confusion',
      variant: 'json_header_form_body',
      ...contentTypeEval,
      status_code: snapshot.status_code,
    });
  }

  if (plannedPhases.has('multipart_confusion') && requestsSent < budget) {
    requestsSent += 1;
    const boundary = 'astranullBoundary7f3a';
    const multipartBody = buildMultipartConfusionBody(BENIGN_CLASS_MARKERS.sqli, boundary);
    const { res, bodyText, error } = await boundedRequest(url, {
      method: 'POST',
      headers: {
        ...DEFAULT_BROWSER_HEADERS,
        'Content-Type': `multipart/form-data; boundary=${boundary}`,
        'Content-Length': String(multipartBody.length),
      },
      body: multipartBody,
      activity_phase: 'multipart_confusion',
    }, timeoutMs, deps);
    const snapshot = error
      ? { ...responseSnapshot(null), error_class: error.name ?? error.code ?? 'probe_failed' }
      : responseSnapshot(res, bodyText, declaredBlockSignature);
    recordTransportError(snapshot);
    recordPhase({
      phase: 'multipart_confusion',
      status_code: snapshot.status_code,
      ...(snapshot.error_class ? { error_class: snapshot.error_class } : {}),
    });
    const multipartEval = isBlockedOrChallenged(snapshot, baseline);
    recordMarkerResult(markerResults, {
      family: 'multipart_confusion',
      variant: 'multipart_form_field',
      ...multipartEval,
      status_code: snapshot.status_code,
    });
  }

  let originBypassAttempted = false;
  let originResponse = null;
  let originError = null;
  let originBodyText = null;
  const canaryNonce = typeof options.canaryNonce === 'string' && options.canaryNonce.trim()
    ? options.canaryNonce.trim()
    : null;
  if (plannedPhases.has('origin_bypass') && directIp && hostname
    && requestsSent < budget && typeof options.originBypassFn === 'function') {
    requestsSent += 1;
    originBypassAttempted = true;
    ({ res: originResponse, error: originError, bodyText: originBodyText = null } = await options.originBypassFn({
      directIp, hostname, timeoutMs, deps, canaryNonce,
    }));
  }
  // Origin-leg failures stay out of transportErrorClasses: they are origin evidence, not edge-marker coverage gaps.
  const originObservation = classifyDirectOriginObservation({
    attempted: originBypassAttempted,
    response: originResponse,
    error: originError,
    bodyText: typeof originBodyText === 'string' ? originBodyText : null,
    baseline,
    expectedNonce: canaryNonce,
    declaredLockdown: options.declaredOriginLockdown ?? null,
    directAddress: directIp,
    scope: { host: hostname, path: '/', port: null },
    observedAt: originBypassAttempted ? new Date().toISOString() : null,
  });
  const originBypassStatus = originBypassAttempted ? (originObservation.status_code ?? 0) : null;
  const directOriginReachable = originObservation.response_observed;
  const networkIngressConfirmed = directOriginReachable
    && originBypassStatus >= 200 && originBypassStatus < 400;
  const applicationSignatureMatch = originObservation.supporting_signals.includes('server_header_match');
  const originBypassConfirmed = originObservation.application_bypass_confirmed;
  if (originBypassAttempted) {
    recordPhase({
      phase: 'origin_bypass',
      status_code: originBypassStatus,
      reachable: directOriginReachable,
      network_ingress_confirmed: networkIngressConfirmed,
      application_signature_match: applicationSignatureMatch,
      observation_outcome: originObservation.outcome,
      denial_signature_id: originObservation.denial_signature?.id ?? null,
      bypass_signal: originBypassConfirmed,
      ...(originObservation.error_class ? { error_class: originObservation.error_class } : {}),
    });
  }

  const attackSnapshot = combined ?? sqli ?? xss ?? pathTraversal ?? baseline;
  const generic = detectGenericWafPresence({ baseline, attack: attackSnapshot, noUserAgent });
  const signalSource = attackSnapshot?.header_names?.length >= baseline?.header_names?.length
    ? attackSnapshot
    : baseline;

  // Structured chain data straight from the resolver. Re-splitting the display string lost IPv6
  // addresses and mislabelled every non-IP token as a CNAME.
  const resolvedIps = dnsResolvedIps;
  const cnameChain = dnsCnameChain;
  const genericDetection = {
    ...wafw00fGenericDetection({
      baseline,
      noUserAgent,
      xss,
      pathTraversal,
      sqli,
      combined,
    }),
    corroborated: generic.detected,
  };
  const edgeSignature = classifyEdgeFingerprint({
    normal: wafw00fResponseEvidence(baseline),
    attack: wafw00fResponseEvidence(combined ?? sqli ?? xss ?? pathTraversal),
    resolvedIps,
    cnameChain,
    dnsObserved,
    genericDetection,
  });

  const vendorClassification = evidenceBackedVendorClassification(classifyWafProductFromSignals({
    header_names: [...new Set([...(baseline?.header_names ?? []), ...(signalSource?.header_names ?? [])])],
    cookie_names: [...new Set([...(baseline?.cookie_names ?? []), ...(signalSource?.cookie_names ?? [])])],
    dns_chain: dnsChainHint ?? '',
    block_page_signature_id: attackSnapshot?.block_page_signature_id ?? baseline?.block_page_signature_id ?? null,
    customer_vendor_hint: options.customerVendorHint ?? null,
    waf_present: generic.detected || specificBlockPageDelta(attackSnapshot, baseline),
  }));

  const vendorChainHints = (vendorClassification.candidates ?? []).slice(0, 3).map((candidate) => ({
    vendor: candidate.vendor,
    product: candidate.product,
    confidence: candidate.confidence,
    matched_signals: candidate.matched_signals ?? [],
  }));

  const wafDetected = Boolean(vendorClassification.best) || generic.detected || edgeSignature.waf_present;
  const evasionBypassSuspected = detectEvasionBypass(markerResults);
  const phasesExecuted = phaseLog.map((entry) => entry.phase);
  const coverageComplete = phasesDropped.length === 0
    && transportErrorClasses.length === 0
    && plan.every((entry) => phasesExecuted.includes(entry.phase));
  const originLockdownConfirmed = originObservation.origin_lockdown_confirmed;
  const posture = buildOutsideInPostureReport({
    wafDetected,
    genericWafDetected: generic.detected,
    markerResults,
    originBypassConfirmed,
    wafRequired: options.wafRequired !== false,
    vendorClassification,
    originLockdownConfirmed,
    evasionBypassSuspected,
    domXssValidation: options.domXssValidation ?? 'external_only',
    edgeSignature,
    coverageComplete,
    probeErrorsPresent: transportErrorClasses.length > 0,
  });

  const directStatus = directOriginStatusFor(originObservation);
  const networkFirewall = {
    status: directStatus,
    direct_origin_reachability: {
      status: directStatus,
      outcome: originObservation.outcome,
      label: originObservation.label,
      reachable: directOriginReachable,
      explicit_denial_observed: originObservation.explicit_denial_observed,
      denial_signature: originObservation.denial_signature,
      response_reason: originObservation.response_reason,
      application_bypass_confirmed: originBypassConfirmed,
      application_bypass_suspected: originObservation.application_bypass_suspected,
      status_code: originBypassStatus,
    },
    port_exposure: {
      status: 'not_tested',
      open_ports: [],
      tested_count: 0,
      reason: 'separate_bounded_port_scan_required',
    },
  };
  const durationMs = Date.now() - started;
  const scanErrorClass = transportErrorClasses.find((value) => /abort|timeout|deadline/i.test(value))
    ? 'timeout'
    : transportErrorClasses[0] ?? null;
  const external_result = scanErrorClass
    ? (scanErrorClass === 'timeout' ? 'timeout' : 'error')
    : originBypassConfirmed || posture.validation_failed
      ? 'connected'
      : posture.validation_passed || (wafDetected && posture.probe_validation_passed)
        ? 'blocked'
        : 'not_run';

  return {
    duration_ms: durationMs,
    requests_sent: requestsSent,
    phases: phaseLog,
    scan_plan: plan.map((entry) => entry.phase),
    phases_planned: phasesPlanned,
    phases_executed: phasesExecuted,
    phases_dropped: phasesDropped,
    coverage_complete: coverageComplete,
    baseline_status_code: baseline?.status_code ?? 0,
    header_names: signalSource?.header_names ?? baseline?.header_names ?? [],
    cookie_names: signalSource?.cookie_names ?? baseline?.cookie_names ?? [],
    block_page_signature_id: attackSnapshot?.block_page_signature_id ?? null,
    block_page_fingerprint_hash: attackSnapshot?.block_page_fingerprint_hash ?? null,
    generic_waf_reasons: generic.reasons,
    marker_probes: markerResults,
    origin_bypass_confirmed: originBypassConfirmed,
    direct_origin_reachable: directOriginReachable,
    origin_bypass_status_code: originBypassStatus,
    origin_bypass_network_ingress_confirmed: networkIngressConfirmed,
    origin_bypass_application_signature_match: applicationSignatureMatch,
    origin_bypass_suspected: originObservation.application_bypass_suspected,
    origin_observation: originObservation,
    network_firewall: networkFirewall,
    ...(scanErrorClass ? { error_class: scanErrorClass } : {}),
    vendor_candidates: (vendorClassification.candidates ?? []).slice(0, 3),
    ...(collectNetworkHints ? { vendor_chain_hints: vendorChainHints } : {}),
    edge_signature: {
      waf_present: edgeSignature.waf_present,
      waf_providers: edgeSignature.waf_providers,
      waf_generic_detected: edgeSignature.waf_generic_detected,
      cdn_detected: edgeSignature.cdn_detected,
      cdn_providers: edgeSignature.cdn_providers,
      cloud_hosted: edgeSignature.cloud_hosted,
      cloud_providers: edgeSignature.cloud_providers,
      dns_observed: edgeSignature.dns_observed,
      attack_response_evaluated: edgeSignature.attack_response_evaluated,
      wafw00f: edgeSignature.wafw00f,
      cdncheck: edgeSignature.cdncheck,
      conflicting_vendor_signals: edgeSignature.conflicting_vendor_signals,
      conflicting_provider_signals: edgeSignature.conflicting_provider_signals,
      stacked_vendor_signals: edgeSignature.stacked_vendor_signals,
      layers: edgeSignature.layers,
      confidence: edgeSignature.confidence,
      evidence_consistency: edgeSignature.evidence_consistency,
      best_vendor: edgeSignature.best_vendor
        ? {
          vendor: edgeSignature.best_vendor.vendor,
          name: edgeSignature.best_vendor.name,
          confidence: edgeSignature.best_vendor.confidence,
          matched_signals: edgeSignature.best_vendor.matched_signals,
        }
        : null,
      vendor_matches: edgeSignature.vendor_matches.slice(0, 5).map((match) => ({
        vendor: match.vendor,
        name: match.name,
        confidence: match.confidence,
        matched_signals: match.matched_signals,
      })),
      ...(dnsObserved
        ? {
            address_matches: edgeSignature.address_matches,
            cname_matches: edgeSignature.cname_matches,
            cname_cdn_matches: edgeSignature.cname_cdn_matches,
            asn_matches: edgeSignature.asn_matches,
            asn: edgeSignature.asn,
          }
        : {}),
    },
    edge_signature_corpus_version: EDGE_SIGNATURE_CORPUS_VERSION,
    network_hints_collected: collectNetworkHints,
    redirect_following_enabled: followRedirects,
    ...(dnsObserved
      ? {
          dns_cname_chain: dnsCnameChain,
          dns_resolved_ips: dnsResolvedIps,
        }
      : {}),
    ...(collectNetworkHints
      ? {
          dns_chain_hint: dnsChainHint,
          tls_protocol_hint: tlsHints.tls_protocol_hint ?? null,
          tls_cipher_hint: tlsHints.tls_cipher_hint ?? null,
        }
      : {}),
    redirect_hops: redirectHops,
    final_url_hostname: finalUrlHostname,
    ...posture,
    external_result,
  };
}
