export type Tone = 'default' | 'success' | 'warn' | 'danger' | 'info' | 'muted';
export type LabelMap = Readonly<Record<string, string>>;
export type ToneMap = Readonly<Record<string, Tone>>;
export type LayerDimension = 'declared_intent' | 'vendor_detection' | 'observed_enforcement' | 'application_identity' | 'suspected_bypass' | 'confirmed_scoped_bypass';

export const PROTECTION_LAYERS: readonly ['waf', 'cdn_edge', 'network_firewall', 'ddos'];
export const LAYER_LABELS: LabelMap;
export const RELATION_KIND_LABELS: LabelMap;
export const EXPECTED_BEHAVIOR_LABELS: LabelMap;
export const LAYER_OUTCOME_LABELS: LabelMap;
export const PATH_OUTCOME_LABELS: LabelMap;
export const PATH_OUTCOME_TONES: ToneMap;
export const FIREWALL_STATUS_LABELS: LabelMap;
export const FIREWALL_STATUS_TONES: ToneMap;
export const FIREWALL_GAP_LABELS: LabelMap;
export const FIREWALL_SIDE_STATE_LABELS: LabelMap;
export const FIREWALL_OBSERVATION_LABELS: LabelMap;
export const PATH_OBSERVATION_LABELS: LabelMap;
export const LAYER_STATE_LABELS: Readonly<Record<LayerDimension, LabelMap>>;
export const LAYER_STATE_TONES: Readonly<Partial<Record<LayerDimension, ToneMap>>>;
export const LAYER_DIMENSION_LABELS: Readonly<Record<LayerDimension, string>>;
export const LIMITATION_LABELS: LabelMap;
export const COMPATIBILITY_REASON_LABELS: LabelMap;
export const FINALIZED_RUN_STATUSES: readonly string[];
export const ACTIVE_RUN_STATUSES: readonly string[];

export function pathObservationLabels(relationKind: unknown): LabelMap;
export function labelFrom(map: LabelMap, value: unknown, fallback?: string): string;
export function toneFrom(map: ToneMap, value: unknown, fallback?: Tone): Tone;
export function containsForbiddenClaim(value: unknown): boolean;
export function layerStateLabel(dimension: string, value: unknown): string;
export function layerStateTone(dimension: string, value: unknown): Tone;
export function limitationLabels(values: unknown): Array<{ id: string; label: string }>;
export function compatibilityReasonLabels(values: unknown): Array<{ id: string; label: string }>;
export function compatibilityView(compatibility: unknown): { state: 'unknown' | 'stale' | 'incompatible' | 'comparable'; label: string; reasons: Array<{ id: string; label: string }> };
export function freshnessView(freshness: unknown, now?: number): { state: 'unknown' | 'stale' | 'fresh'; label: string };
export function summaryView(summary: unknown, kind: 'path_validation' | 'firewall_change'): {
  total: number | null;
  evaluated: number | null;
  accepted: boolean;
  partial: boolean;
  label: string;
  byStatus: Record<string, unknown>;
  gaps: Record<string, unknown>;
};
export function isFinalizedRun(run: unknown): boolean;
export function isActiveRun(run: unknown): boolean;
export function runSelectionBlocker(run: unknown, allowedTargetIds: readonly string[]): string;
export function comparisonProgress(comparison: unknown, runStatuses?: Record<string, string>): {
  total: number;
  started: number;
  finished: number;
  running: number;
  skipped: number;
  activeRunIds: string[];
  status: string;
};
export type EntryPathDraft = {
  relation_kind: string;
  entry_target_id: string;
  expected_behavior: string;
  required_layers: string[];
  origin_binding_id: string;
  owner: string;
  purpose: string;
};
export type EntryPathCreateBody = {
  entry_target_id: string;
  relation_kind: string;
  owner: string;
  purpose: string;
  expected_behavior: string;
  required_layers: string[];
  origin_binding_id: string | null;
};
export function entryPathDraftErrors(draft: Partial<EntryPathDraft>, anchorTargetId: string): Partial<Record<keyof EntryPathDraft, string>>;
export function entryPathCreateBody(draft: Partial<EntryPathDraft>): EntryPathCreateBody;
export type FirewallDraft = {
  destination_target_id: string;
  protocol: string;
  port: string;
  service: string;
  service_port: string;
  service_path: string;
  expected: string;
  source_perspective: string;
  change_id: string;
  owner: string;
  pre_destination_target_id: string;
};
export type FirewallExpectationBody = {
  destination_target_id: string;
  protocol: string;
  port?: number | null;
  service_endpoint?: { service: string; port: number | null; path?: string };
  expected: string;
  source_perspective: string;
  change_id: string;
  owner?: string;
  pre_post_mapping?: { pre_destination_target_id: string; post_destination_target_id: string; declared_by_customer: true };
};
export function firewallDraftErrors(draft: Partial<FirewallDraft>): Partial<Record<keyof FirewallDraft, string>>;
export function firewallExpectationBody(draft: Partial<FirewallDraft>): FirewallExpectationBody;
export function firewallScopeText(expectation: unknown): string;
export function failureCopy(failure: unknown, subject?: string): string;
export function writeErrorCopy(code: string, fallback: string): string;
export function splitEntryPathsByAnchor<T extends { anchor_target_id: string }>(items: readonly T[], targetId: string): { anchored: T[]; referenced: T[] };
export function authorizationView(path: unknown): { authorized: boolean | null; label: string; tone: Tone };
