/** Safe check catalog — metadata-only validation; no live attack traffic in developer validation mode. */

export const ALLOWED_PROBE_PROFILE_KINDS = Object.freeze([
  'http_head',
  'tcp_connect',
  'dns_resolve',
  'metadata_marker',
  'udp_probe',
  'quic_reachability',
  'alert_webhook_ping',
  'ops_readiness',
  'ownership_challenge',
  'tls_session',
  'http2_settings',
]);

const ALLOWED_OPS_READINESS_SCENARIOS = new Set(['runbook_contacts', 'kill_switch_readiness']);

const ALLOWED_PROBE_KINDS = new Set(ALLOWED_PROBE_PROFILE_KINDS);
export const MAX_PROBE_PROFILE_TIMEOUT_MS = 5000;
export const MAX_PROBE_PROFILE_REQUESTS = 5;

export const WAF_SAFE_PROBE_METADATA_KEYS = Object.freeze([
  'scenario_family',
  'marker_type',
  'expected_action',
  'nonce_hash_only',
  'collect',
]);

const ALLOWED_WAF_SCENARIO_FAMILIES = new Set([
  'marker',
  'fingerprint',
  'origin_bypass',
  'rate_limit_marker',
]);

const ALLOWED_WAF_MARKER_TYPES = new Set(['header', 'path', 'query', 'user_agent']);

const ALLOWED_WAF_EXPECTED_ACTIONS = new Set([
  'block',
  'challenge',
  'rate_limit',
  'log_only_expected',
  'allow_expected',
]);

const ALLOWED_WAF_COLLECT_KEYS = new Set([
  'status_code',
  'server_header',
  'waf_product_hint',
  'tls_fingerprint_hint',
]);

export const WAF_SAFE_CHECK_IDS = Object.freeze([
  'l7.waf_marker_rule.safe',
  'waf.fingerprint.safe',
  'waf.marker_rule.safe',
  'waf.origin_bypass.safe',
  'waf.low_rate_limit.safe',
]);

function applyWafSafeProbeMetadata(profile, meta = {}) {
  const scenario = meta.scenario_family;
  if (typeof scenario === 'string' && ALLOWED_WAF_SCENARIO_FAMILIES.has(scenario)) {
    profile.scenario_family = scenario;
  }
  const markerType = meta.marker_type;
  if (typeof markerType === 'string' && ALLOWED_WAF_MARKER_TYPES.has(markerType)) {
    profile.marker_type = markerType;
  }
  const expected = meta.expected_action;
  if (typeof expected === 'string' && ALLOWED_WAF_EXPECTED_ACTIONS.has(expected)) {
    profile.expected_action = expected;
  }
  if (meta.nonce_hash_only === true) {
    profile.nonce_hash_only = true;
  }
  if (Array.isArray(meta.collect)) {
    const collect = meta.collect
      .filter((key) => typeof key === 'string' && ALLOWED_WAF_COLLECT_KEYS.has(key))
      .slice(0, 8);
    if (collect.length > 0) profile.collect = collect;
  }
}

export function buildProbeProfile({
  kind,
  max_requests = 1,
  timeout_ms = 5000,
  marker,
  scenario,
  scenario_family,
  marker_type,
  expected_action,
  nonce_hash_only,
  collect,
} = {}) {
  if (!ALLOWED_PROBE_KINDS.has(kind)) {
    throw new Error(`invalid probe profile kind: ${kind}`);
  }
  const cappedRequests = Math.min(
    Math.max(1, Number(max_requests) || 1),
    MAX_PROBE_PROFILE_REQUESTS,
  );
  const cappedTimeout = Math.min(
    Math.max(100, Number(timeout_ms) || MAX_PROBE_PROFILE_TIMEOUT_MS),
    MAX_PROBE_PROFILE_TIMEOUT_MS,
  );
  const profile = {
    kind,
    max_requests: cappedRequests,
    timeout_ms: cappedTimeout,
  };
  if (marker) profile.marker = String(marker).slice(0, 128);
  if (kind === 'http_head') profile.method = 'HEAD';
  if (kind === 'ops_readiness' && typeof scenario === 'string' && ALLOWED_OPS_READINESS_SCENARIOS.has(scenario)) {
    profile.scenario = scenario;
  }
  applyWafSafeProbeMetadata(profile, {
    scenario_family,
    marker_type,
    expected_action,
    nonce_hash_only,
    collect,
  });
  return profile;
}

const DEFAULT_WAF_MARKER_PROBE_PROFILE = Object.freeze({
  kind: 'http_head',
  max_requests: 1,
  timeout_ms: 5000,
  marker: 'astranull-safe-marker',
  scenario_family: 'marker',
  marker_type: 'header',
  expected_action: 'block',
  nonce_hash_only: true,
  collect: ['status_code', 'waf_product_hint'],
});

const DEFAULT_SAFE_STOP_CONDITIONS = Object.freeze([
  'max_events_reached',
  'max_duration_elapsed',
  'customer_cancel',
  'tenant_kill_switch',
]);

const DEFAULT_SOC_STOP_CONDITIONS = Object.freeze([
  'soc_kill_switch',
  'abort_criteria_met',
  'provider_stop_signal',
  'max_approved_duration',
]);

function safeCheck(def) {
  const probe_profile = buildProbeProfile(
    def.probe_profile ?? { kind: 'metadata_marker', max_requests: 1, timeout_ms: 5000 },
  );
  const stop_conditions = def.stop_conditions ?? [...DEFAULT_SAFE_STOP_CONDITIONS];
  const safety_constraints = {
    max_events: 3,
    max_duration_seconds: 90,
    max_concurrent_runs_per_target_group: 1,
    ...(def.safety_constraints ?? {}),
  };
  return {
    safety_class: 'safe',
    risk_class: 'safe',
    prerequisites: def.prerequisites ?? [],
    remediation_template: def.remediation_template ?? 'Review edge protection and agent placement for this vector.',
    explanation_template: def.explanation_template ?? 'Simulated probe metadata correlated with agent observation.',
    supported_targets: def.supported_targets ?? ['fqdn'],
    required_customer_setup: def.required_customer_setup ?? [],
    evidence_required: def.evidence_required ?? ['probe_result', 'agent_observation'],
    stop_conditions,
    verdict_logic:
      def.verdict_logic ??
      'Verdict when probe external_result and agent observation align with target expected_behavior.',
    safety_constraints,
    probe_profile,
    ...def,
    stop_conditions,
    safety_constraints,
    probe_profile,
  };
}

function socGated(def) {
  const { probe_profile: _ignoredProbe, ...rest } = def;
  const required_customer_setup = rest.required_customer_setup ?? [
    'soc_authorization_pack',
    'declared_target_group_scope',
  ];
  const evidence_required = rest.evidence_required ?? ['approval_artifact', 'soc_runbook_ack'];
  const stop_conditions = rest.stop_conditions ?? [...DEFAULT_SOC_STOP_CONDITIONS];
  const safety_constraints = { customer_runnable: false, ...(rest.safety_constraints ?? {}) };
  return {
    safety_class: 'soc_gated',
    risk_class: 'soc_gated',
    prerequisites: ['soc_approval_required'],
    remediation_template:
      rest.remediation_template ?? 'Submit a SOC-gated high-scale request with authorization pack.',
    explanation_template: rest.explanation_template ?? 'Not runnable via customer test-runs API.',
    required_customer_setup,
    evidence_required,
    stop_conditions,
    safety_constraints,
    ...rest,
    safety_class: 'soc_gated',
    risk_class: 'soc_gated',
    required_customer_setup,
    evidence_required,
    stop_conditions,
    safety_constraints,
  };
}

export const CHECK_CATALOG = [
  safeCheck({
    check_id: 'origin.direct_reachability.safe',
    version: '1.0.0',
    name: 'Direct Origin Reachability (Safe)',
    vector_family: 'origin',
    description: 'Metadata simulation of direct-origin reachability without live flood traffic.',
    required_agent_modes: ['canary', 'packet', 'heartbeat'],
    supported_targets: ['fqdn', 'ip', 'url'],
    required_customer_setup: ['declared_origin_target', 'agent_on_origin_path'],
    evidence_required: ['probe_result', 'agent_observation'],
    verdict_logic: 'Block verdict when probe connects externally but agent observes origin reach; pass when both show edge block.',
    probe_profile: { kind: 'http_head', max_requests: 1, timeout_ms: 5000, marker: 'astranull-safe-marker' },
    safety_constraints: { max_events: 3, max_duration_seconds: 120, max_concurrent_runs_per_target_group: 1 },
    default_expected_behavior: 'must_block_before_origin',
    probe_simulation_profile: 'external_connected',
  }),
  safeCheck({
    check_id: 'origin.direct_bypass.safe',
    version: '1.0.0',
    name: 'Direct-Origin Bypass (Safe)',
    vector_family: 'origin',
    description: 'Metadata-only simulated probe validates whether direct-origin path would reach an observation point.',
    required_agent_modes: ['canary', 'packet', 'heartbeat'],
    supported_targets: ['fqdn', 'ip', 'url'],
    required_customer_setup: ['declared_origin_target', 'agent_on_origin_path'],
    evidence_required: ['probe_result', 'agent_observation'],
    verdict_logic: 'Correlate single HEAD probe reachability with agent path observation against expected_behavior.',
    probe_profile: { kind: 'http_head', max_requests: 1, timeout_ms: 5000, marker: 'astranull-safe-marker' },
    safety_constraints: { max_events: 3, max_duration_seconds: 120, max_concurrent_runs_per_target_group: 1 },
    default_expected_behavior: 'must_block_before_origin',
    probe_simulation_profile: 'external_connected',
  }),
  safeCheck({
    check_id: 'origin.host_sni_bypass.safe',
    version: '1.0.0',
    name: 'Host/SNI Bypass (Safe)',
    vector_family: 'origin',
    description: 'Simulated host/SNI mismatch metadata to detect origin bypass routing.',
    required_agent_modes: ['canary', 'heartbeat'],
    supported_targets: ['fqdn', 'url'],
    required_customer_setup: ['declared_host_sni_target'],
    evidence_required: ['probe_result', 'agent_observation'],
    verdict_logic: 'HEAD probe with declared host/SNI metadata must not reach origin when protection is effective.',
    probe_profile: { kind: 'http_head', max_requests: 1, timeout_ms: 5000, marker: 'astranull-safe-marker' },
    safety_constraints: { max_events: 3, max_duration_seconds: 90, max_concurrent_runs_per_target_group: 1 },
    default_expected_behavior: 'must_block_before_origin',
    probe_simulation_profile: 'external_connected',
  }),
  safeCheck({
    check_id: 'path.protected_canary.safe',
    version: '1.0.0',
    name: 'Protected-Path Canary (Safe)',
    vector_family: 'path',
    description: 'Harmless labeled canary request through protected path (simulated probe metadata).',
    required_agent_modes: ['canary'],
    prerequisites: ['agent_mode:canary'],
    supported_targets: ['url', 'fqdn', 'canary'],
    required_customer_setup: ['canary_route_behind_protected_path'],
    evidence_required: ['probe_result', 'agent_observation'],
    verdict_logic: 'Canary marker probe should reach canary only when protected path routes correctly.',
    probe_profile: { kind: 'http_head', max_requests: 1, timeout_ms: 5000, marker: 'astranull-safe-marker' },
    safety_constraints: { max_events: 3, max_duration_seconds: 120, max_concurrent_runs_per_target_group: 1 },
    default_expected_behavior: 'must_reach_canary',
    probe_simulation_profile: 'external_connected',
  }),
  safeCheck({
    check_id: 'l3.forbidden_tcp_port.safe',
    version: '1.0.0',
    name: 'Forbidden TCP Port (Safe)',
    vector_family: 'l3_l4',
    description: 'Low-rate reachability metadata check for a forbidden TCP port (simulated).',
    required_agent_modes: ['packet', 'mirror', 'heartbeat'],
    supported_targets: ['ip', 'fqdn'],
    required_customer_setup: ['declared_forbidden_tcp_port', 'expected_block_behavior'],
    evidence_required: ['probe_result', 'agent_observation'],
    verdict_logic: 'Single TCP connect attempt must be blocked when deny rules are effective.',
    probe_profile: { kind: 'tcp_connect', max_requests: 1, timeout_ms: 5000 },
    safety_constraints: { max_events: 3, max_duration_seconds: 60, max_concurrent_runs_per_target_group: 1 },
    default_expected_behavior: 'must_block_before_origin',
    probe_simulation_profile: 'external_blocked',
  }),
  safeCheck({
    check_id: 'l3.forbidden_udp_port.safe',
    version: '1.0.0',
    name: 'Forbidden UDP Port (Safe)',
    vector_family: 'l3_l4',
    description: 'Single bounded UDP datagram to a declared forbidden port (no amplification).',
    required_agent_modes: ['packet', 'mirror', 'heartbeat'],
    supported_targets: ['ip', 'fqdn'],
    required_customer_setup: ['declared_forbidden_udp_port', 'agent_packet_or_mirror_mode'],
    evidence_required: ['probe_result', 'agent_observation'],
    verdict_logic: 'One labeled UDP datagram must be blocked or filtered when deny rules are effective.',
    probe_profile: { kind: 'udp_probe', max_requests: 1, timeout_ms: 5000 },
    safety_constraints: { max_events: 3, max_duration_seconds: 60, max_concurrent_runs_per_target_group: 1 },
    default_expected_behavior: 'must_block_before_origin',
    probe_simulation_profile: 'external_blocked',
  }),
  safeCheck({
    check_id: 'l3.basic_deny_rule.safe',
    version: '1.0.0',
    name: 'Basic Deny-Rule Validation (Safe)',
    vector_family: 'l3_l4',
    description: 'Simulated deny-rule probe metadata correlated with block/penetrate verdict.',
    required_agent_modes: ['packet', 'heartbeat'],
    supported_targets: ['ip', 'fqdn'],
    required_customer_setup: ['declared_deny_rule_target'],
    evidence_required: ['probe_result', 'agent_observation'],
    verdict_logic: 'One bounded TCP connect plus agent observation confirms deny rule enforcement.',
    probe_profile: { kind: 'tcp_connect', max_requests: 1, timeout_ms: 5000 },
    safety_constraints: { max_events: 3, max_duration_seconds: 60, max_concurrent_runs_per_target_group: 1 },
    default_expected_behavior: 'must_block_before_origin',
    probe_simulation_profile: 'external_blocked',
  }),
  safeCheck({
    check_id: 'dns.authoritative_response.safe',
    version: '1.0.0',
    name: 'DNS Authoritative Response (Safe)',
    vector_family: 'dns',
    description: 'Authoritative DNS response metadata validation (no live recursion abuse).',
    required_agent_modes: ['heartbeat'],
    supported_targets: ['fqdn', 'dns'],
    required_customer_setup: ['declared_authoritative_zone'],
    evidence_required: ['probe_result'],
    verdict_logic: 'Single DNS lookup must return healthy authoritative response metadata for declared name.',
    probe_profile: { kind: 'dns_resolve', max_requests: 1, timeout_ms: 5000 },
    safety_constraints: { max_events: 3, max_duration_seconds: 60, max_concurrent_runs_per_target_group: 1 },
    default_expected_behavior: 'must_block_before_origin',
    probe_simulation_profile: 'external_blocked',
  }),
  safeCheck({
    check_id: 'dns.random_prefix_nxdomain.safe',
    version: '1.0.0',
    name: 'DNS Random-Prefix / NXDOMAIN (Safe)',
    vector_family: 'dns',
    description: 'NXDOMAIN/random-prefix signal metadata for resolver hygiene.',
    required_agent_modes: ['heartbeat'],
    supported_targets: ['fqdn', 'dns'],
    required_customer_setup: ['declared_zone_for_random_prefix'],
    evidence_required: ['probe_result'],
    verdict_logic: 'One labeled random-prefix lookup observes NXDOMAIN or mitigation behavior without high QPS.',
    probe_profile: { kind: 'dns_resolve', max_requests: 1, timeout_ms: 5000 },
    safety_constraints: { max_events: 3, max_duration_seconds: 60, max_concurrent_runs_per_target_group: 1 },
    default_expected_behavior: 'must_block_before_origin',
    probe_simulation_profile: 'external_blocked',
  }),
  safeCheck({
    check_id: 'dns.open_recursion_behavior.safe',
    version: '1.0.0',
    name: 'Open Recursion Behavior (Safe)',
    vector_family: 'dns',
    description: 'Open recursion exposure metadata check (simulated, bounded).',
    required_agent_modes: ['heartbeat'],
    supported_targets: ['fqdn', 'dns', 'ip'],
    required_customer_setup: ['declared_resolver_target'],
    evidence_required: ['probe_result'],
    verdict_logic: 'Bounded resolver lookup metadata indicates open recursion only when customer declared intent.',
    probe_profile: { kind: 'dns_resolve', max_requests: 1, timeout_ms: 5000 },
    safety_constraints: { max_events: 3, max_duration_seconds: 60, max_concurrent_runs_per_target_group: 1 },
    default_expected_behavior: 'must_block_before_origin',
    probe_simulation_profile: 'external_blocked',
  }),
  safeCheck({
    check_id: 'l7.waf_marker_rule.safe',
    version: '1.0.0',
    name: 'WAF Marker Rule (Safe)',
    vector_family: 'l7',
    description: 'Customer-defined WAF marker rule validation via harmless metadata probe.',
    required_agent_modes: ['canary', 'heartbeat'],
    supported_targets: ['url', 'fqdn'],
    required_customer_setup: ['declared_waf_asset', 'customer_waf_marker_rule'],
    evidence_required: ['probe_result', 'agent_observation'],
    verdict_logic: 'HEAD probe with harmless marker should be blocked or challenged when WAF rule is active.',
    probe_profile: { ...DEFAULT_WAF_MARKER_PROBE_PROFILE },
    safety_constraints: { max_events: 3, max_duration_seconds: 90, max_concurrent_runs_per_target_group: 1 },
    default_expected_behavior: 'must_block_before_origin',
    probe_simulation_profile: 'external_blocked',
  }),
  safeCheck({
    check_id: 'waf.fingerprint.safe',
    version: '1.0.0',
    name: 'WAF Fingerprint (Safe)',
    vector_family: 'waf',
    description: 'Bounded HEAD metadata to infer WAF presence from response class headers — no bypass attempts.',
    required_agent_modes: ['heartbeat'],
    supported_targets: ['url', 'fqdn'],
    required_customer_setup: ['declared_waf_asset', 'customer_approves_waf_fingerprint_probe'],
    evidence_required: ['probe_result'],
    verdict_logic: 'Up to three HEAD probes collect server/WAF hint metadata only; no auth bypass or high rate.',
    probe_profile: {
      kind: 'http_head',
      max_requests: 3,
      timeout_ms: 5000,
      scenario_family: 'fingerprint',
      expected_action: 'log_only_expected',
      nonce_hash_only: true,
      collect: ['status_code', 'server_header', 'waf_product_hint', 'tls_fingerprint_hint'],
    },
    safety_constraints: { max_events: 3, max_duration_seconds: 90, max_concurrent_runs_per_target_group: 1 },
    default_expected_behavior: 'must_block_before_origin',
    probe_simulation_profile: 'external_blocked',
  }),
  safeCheck({
    check_id: 'waf.marker_rule.safe',
    version: '1.0.0',
    name: 'WAF Marker Rule Posture (Safe)',
    vector_family: 'waf',
    description: 'WAF posture alias for customer-configured harmless marker rules (signed worker profile).',
    required_agent_modes: ['canary', 'heartbeat'],
    supported_targets: ['url', 'fqdn'],
    required_customer_setup: ['declared_waf_asset', 'customer_waf_marker_rule'],
    evidence_required: ['probe_result', 'agent_observation'],
    verdict_logic: 'HEAD probe with declared harmless marker should be blocked or challenged when WAF rule is active.',
    probe_profile: { ...DEFAULT_WAF_MARKER_PROBE_PROFILE },
    safety_constraints: { max_events: 3, max_duration_seconds: 90, max_concurrent_runs_per_target_group: 1 },
    default_expected_behavior: 'must_block_before_origin',
    probe_simulation_profile: 'external_blocked',
  }),
  safeCheck({
    check_id: 'waf.origin_bypass.safe',
    version: '1.0.0',
    name: 'WAF Origin Bypass (Safe)',
    vector_family: 'waf',
    description: 'Customer-approved direct-origin path metadata with agent observation — no volumetric traffic.',
    required_agent_modes: ['canary', 'packet', 'heartbeat'],
    supported_targets: ['fqdn', 'ip', 'url'],
    required_customer_setup: [
      'declared_waf_asset',
      'declared_direct_origin_target',
      'agent_on_origin_path',
    ],
    evidence_required: ['probe_result', 'agent_observation'],
    verdict_logic: 'Single bounded HEAD on approved direct path must not reach origin when edge WAF is effective.',
    probe_profile: {
      kind: 'http_head',
      max_requests: 1,
      timeout_ms: 5000,
      marker: 'astranull-safe-marker',
      scenario_family: 'origin_bypass',
      marker_type: 'header',
      expected_action: 'block',
      nonce_hash_only: true,
      collect: ['status_code'],
    },
    safety_constraints: { max_events: 3, max_duration_seconds: 120, max_concurrent_runs_per_target_group: 1 },
    default_expected_behavior: 'must_block_before_origin',
    probe_simulation_profile: 'external_connected',
  }),
  safeCheck({
    check_id: 'waf.low_rate_limit.safe',
    version: '1.0.0',
    name: 'WAF Low-Rate Limit Readiness (Safe)',
    vector_family: 'waf',
    description: 'Spaced low-rate HEAD sequence on declared endpoint to observe WAF rate-limit signals.',
    required_agent_modes: ['canary', 'heartbeat'],
    supported_targets: ['url', 'fqdn'],
    required_customer_setup: ['declared_waf_asset', 'customer_rate_limit_threshold'],
    evidence_required: ['probe_result', 'agent_observation'],
    verdict_logic: 'Up to five spaced HEAD probes observe rate-limit or challenge signals without load generation.',
    probe_profile: {
      kind: 'http_head',
      max_requests: 5,
      timeout_ms: 5000,
      marker: 'astranull-safe-marker',
      scenario_family: 'rate_limit_marker',
      marker_type: 'header',
      expected_action: 'rate_limit',
      nonce_hash_only: true,
      collect: ['status_code', 'waf_product_hint'],
    },
    safety_constraints: { max_events: 5, max_duration_seconds: 120, max_concurrent_runs_per_target_group: 1 },
    default_expected_behavior: 'must_block_before_origin',
    probe_simulation_profile: 'external_blocked',
  }),
  safeCheck({
    check_id: 'l7.http_method_restriction.safe',
    version: '1.0.0',
    name: 'HTTP Method Restriction (Safe)',
    vector_family: 'l7',
    description: 'Unusual HTTP method restriction metadata check (TRACE/unsafe methods).',
    required_agent_modes: ['canary', 'heartbeat'],
    supported_targets: ['url', 'fqdn'],
    required_customer_setup: ['url_target_with_method_policy'],
    evidence_required: ['probe_result'],
    verdict_logic: 'Safe HEAD-only probe metadata; method policy validated via edge response codes (no unsafe methods sent).',
    probe_profile: { kind: 'http_head', max_requests: 1, timeout_ms: 5000 },
    safety_constraints: { max_events: 3, max_duration_seconds: 90, max_concurrent_runs_per_target_group: 1 },
    default_expected_behavior: 'must_block_before_origin',
    probe_simulation_profile: 'external_blocked',
  }),
  safeCheck({
    check_id: 'l7.header_size_boundary.safe',
    version: '1.0.0',
    name: 'Header/Size Boundary (Safe)',
    vector_family: 'l7',
    description: 'Header/size boundary metadata validation without oversized payloads.',
    required_agent_modes: ['canary', 'heartbeat'],
    supported_targets: ['url', 'fqdn'],
    required_customer_setup: ['url_target'],
    evidence_required: ['probe_result'],
    verdict_logic: 'Minimal HEAD probe confirms edge handles boundary policy without oversized request bodies.',
    probe_profile: { kind: 'http_head', max_requests: 1, timeout_ms: 5000 },
    safety_constraints: { max_events: 3, max_duration_seconds: 90, max_concurrent_runs_per_target_group: 1 },
    default_expected_behavior: 'must_block_before_origin',
    probe_simulation_profile: 'external_blocked',
  }),
  safeCheck({
    check_id: 'l7.low_rate_rate_limit.safe',
    version: '1.0.0',
    name: 'Low-Rate Rate-Limit Check (Safe)',
    vector_family: 'l7',
    description: 'Controlled low-rate metadata sequence to observe rate-limit signals (bounded).',
    required_agent_modes: ['canary', 'heartbeat'],
    supported_targets: ['url', 'fqdn'],
    required_customer_setup: ['customer_rate_limit_threshold'],
    evidence_required: ['probe_result', 'agent_observation'],
    verdict_logic: 'Up to five spaced HEAD probes observe rate-limit signals without load generation.',
    probe_profile: { kind: 'http_head', max_requests: 5, timeout_ms: 5000, marker: 'astranull-safe-marker' },
    safety_constraints: { max_events: 5, max_duration_seconds: 120, max_concurrent_runs_per_target_group: 1 },
    default_expected_behavior: 'must_block_before_origin',
    probe_simulation_profile: 'external_blocked',
  }),
  safeCheck({
    check_id: 'tls.profile_exposure.safe',
    version: '1.0.0',
    name: 'TLS Profile Exposure (Safe)',
    vector_family: 'tls',
    description: 'TLS handshake/profile exposure metadata at safe scale.',
    required_agent_modes: ['heartbeat'],
    supported_targets: ['fqdn', 'url'],
    required_customer_setup: ['tls_terminated_endpoint'],
    evidence_required: ['probe_result'],
    verdict_logic: 'Single HTTPS HEAD reveals TLS termination metadata without handshake flooding.',
    probe_profile: { kind: 'http_head', max_requests: 1, timeout_ms: 5000 },
    safety_constraints: { max_events: 3, max_duration_seconds: 90, max_concurrent_runs_per_target_group: 1 },
    default_expected_behavior: 'must_block_before_origin',
    probe_simulation_profile: 'external_blocked',
  }),
  safeCheck({
    check_id: 'protocol.http2_readiness.safe',
    version: '1.0.0',
    name: 'HTTP/2 Readiness Metadata (Safe)',
    vector_family: 'protocol',
    description: 'HTTP/2 readiness and protection metadata (no load generation).',
    required_agent_modes: ['heartbeat'],
    supported_targets: ['url', 'fqdn'],
    required_customer_setup: ['http2_enabled_endpoint'],
    evidence_required: ['probe_result'],
    verdict_logic: 'Bounded HEAD over TLS collects protocol readiness metadata only.',
    probe_profile: { kind: 'http_head', max_requests: 1, timeout_ms: 5000 },
    safety_constraints: { max_events: 3, max_duration_seconds: 90, max_concurrent_runs_per_target_group: 1 },
    default_expected_behavior: 'must_block_before_origin',
    probe_simulation_profile: 'external_blocked',
  }),
  safeCheck({
    check_id: 'protocol.http3_quic_exposure.safe',
    version: '1.0.0',
    name: 'HTTP/3 QUIC Exposure (Safe)',
    vector_family: 'protocol',
    description: 'Bounded QUIC reachability via Alt-Svc discovery and a single UDP-443 datagram.',
    required_agent_modes: ['heartbeat'],
    supported_targets: ['fqdn', 'url'],
    required_customer_setup: ['declared_quic_exposure_intent'],
    evidence_required: ['probe_result', 'health_signal'],
    verdict_logic: 'HTTPS Alt-Svc hint plus one UDP datagram documents QUIC exposure without a QUIC flood.',
    probe_profile: { kind: 'quic_reachability', max_requests: 2, timeout_ms: 5000 },
    safety_constraints: { max_events: 3, max_duration_seconds: 90, max_concurrent_runs_per_target_group: 1 },
    default_expected_behavior: 'must_block_before_origin',
    probe_simulation_profile: 'external_blocked',
  }),
  safeCheck({
    check_id: 'ops.alert_workflow_marker.safe',
    version: '1.0.0',
    name: 'Alert Workflow Webhook Ping (Safe)',
    vector_family: 'operations',
    description: 'Posts a harmless webhook ping to validate alert pipeline delivery.',
    required_agent_modes: ['heartbeat'],
    supported_targets: ['canary', 'fqdn'],
    required_customer_setup: ['alert_webhook_or_siem_hook'],
    evidence_required: ['probe_result'],
    verdict_logic: 'Single POST to the declared alert webhook must return HTTP 2xx.',
    probe_profile: { kind: 'alert_webhook_ping', max_requests: 1, timeout_ms: 5000, marker: 'astranull-safe-marker' },
    safety_constraints: { max_events: 3, max_duration_seconds: 60, max_concurrent_runs_per_target_group: 1 },
    default_expected_behavior: 'must_block_before_origin',
    probe_simulation_profile: 'external_connected',
  }),
  safeCheck({
    check_id: 'ops.runbook_contact_validation.safe',
    version: '1.0.0',
    name: 'Runbook / Emergency Contact Validation (Safe)',
    vector_family: 'operations',
    description: 'Validates accepted support_readiness evidence for runbook owners and emergency contacts.',
    required_agent_modes: ['heartbeat'],
    supported_targets: ['canary', 'fqdn'],
    required_customer_setup: ['current_runbook_artifact', 'emergency_contact_roster'],
    evidence_required: ['probe_result', 'runbook_version_audit', 'contact_ack_evidence'],
    verdict_logic: 'Accepted support_readiness evidence must pass metadata validation for on-call and escalation contacts.',
    probe_profile: { kind: 'ops_readiness', scenario: 'runbook_contacts', max_requests: 1, timeout_ms: 5000 },
    safety_constraints: { max_events: 3, max_duration_seconds: 60, max_concurrent_runs_per_target_group: 1 },
    default_expected_behavior: 'must_block_before_origin',
    probe_simulation_profile: 'external_connected',
  }),
  safeCheck({
    check_id: 'ops.kill_switch_drill.safe',
    version: '1.0.0',
    name: 'Kill Switch Drill Readiness (Safe)',
    vector_family: 'operations',
    description: 'Read-only kill-switch readiness dry-run — verifies state/audit/drill evidence without activation.',
    required_agent_modes: ['heartbeat'],
    supported_targets: ['canary', 'fqdn'],
    required_customer_setup: ['kill_switch_runbook', 'declared_drill_scope'],
    evidence_required: ['probe_result', 'stop_event_audit'],
    verdict_logic: 'Tenant must have kill-switch state, audit trail, or accepted drill evidence; kill switch is never activated.',
    probe_profile: { kind: 'ops_readiness', scenario: 'kill_switch_readiness', max_requests: 1, timeout_ms: 5000 },
    safety_constraints: { max_events: 3, max_duration_seconds: 60, max_concurrent_runs_per_target_group: 1 },
    default_expected_behavior: 'must_block_before_origin',
    probe_simulation_profile: 'external_connected',
  }),
  safeCheck({
    check_id: 'l3.ipv6_reachability.safe',
    version: '1.0.0',
    name: 'IPv6 Declared Reachability (Safe)',
    vector_family: 'l3_l4',
    description: 'Low-rate reachability metadata for customer-declared IPv6 targets only (no volumetric traffic).',
    required_agent_modes: ['packet', 'heartbeat'],
    supported_targets: ['ip', 'fqdn'],
    required_customer_setup: ['declared_ipv6_target', 'expected_ipv6_protection_behavior'],
    evidence_required: ['probe_result', 'agent_observation'],
    stop_conditions: ['max_events_reached', 'max_duration_elapsed', 'customer_cancel', 'tenant_kill_switch'],
    verdict_logic: 'Single bounded TCP connect or metadata marker confirms IPv6 path policy without connection exhaustion.',
    probe_profile: { kind: 'tcp_connect', max_requests: 1, timeout_ms: 5000 },
    safety_constraints: { max_events: 3, max_duration_seconds: 60, max_concurrent_runs_per_target_group: 1 },
    default_expected_behavior: 'must_block_before_origin',
    probe_simulation_profile: 'external_blocked',
  }),
  safeCheck({
    check_id: 'dns.amplification_exposure.safe',
    version: '1.0.0',
    name: 'DNS Amplification Exposure (Safe Metadata)',
    vector_family: 'dns',
    description: 'Validates reflector/amplification exposure via config and response-class metadata only — no reflection traffic.',
    required_agent_modes: ['heartbeat'],
    supported_targets: ['fqdn', 'dns', 'ip'],
    required_customer_setup: ['declared_authoritative_or_resolver_target', 'customer_amplification_policy_intent'],
    evidence_required: ['probe_result', 'health_signal'],
    stop_conditions: ['max_events_reached', 'max_duration_elapsed', 'customer_cancel', 'tenant_kill_switch'],
    verdict_logic: 'Bounded DNS resolve collects response-size/class metadata; verdict when target is not usable as an unintended amplifier.',
    remediation_template: 'Restrict open resolvers, limit ANY/TXT responses, and align with provider anti-amplification guidance.',
    probe_profile: { kind: 'dns_resolve', max_requests: 1, timeout_ms: 5000 },
    safety_constraints: { max_events: 3, max_duration_seconds: 60, max_concurrent_runs_per_target_group: 1 },
    default_expected_behavior: 'must_block_before_origin',
    probe_simulation_profile: 'external_blocked',
  }),
  safeCheck({
    check_id: 'dns.dnssec_expensive_query.safe',
    version: '1.0.0',
    name: 'DNSSEC / Expensive Query Readiness (Safe)',
    vector_family: 'dns',
    description: 'Low-rate declared DNS query type readiness without high QPS or resolver abuse.',
    required_agent_modes: ['heartbeat'],
    supported_targets: ['fqdn', 'dns'],
    required_customer_setup: ['declared_dns_query_type', 'authoritative_or_resolver_target'],
    evidence_required: ['probe_result'],
    stop_conditions: ['max_events_reached', 'max_duration_elapsed', 'customer_cancel', 'tenant_kill_switch'],
    verdict_logic: 'One labeled DNS lookup observes latency/RCODE for expensive query class without sustained load.',
    probe_profile: { kind: 'dns_resolve', max_requests: 1, timeout_ms: 5000 },
    safety_constraints: { max_events: 3, max_duration_seconds: 60, max_concurrent_runs_per_target_group: 1 },
    default_expected_behavior: 'must_block_before_origin',
    probe_simulation_profile: 'external_blocked',
  }),
  safeCheck({
    check_id: 'dns.secondary_failover.safe',
    version: '1.0.0',
    name: 'Secondary DNS Failover (Safe)',
    vector_family: 'dns',
    description: 'Customer-declared secondary DNS and failover path metadata validation (no failover stress).',
    required_agent_modes: ['heartbeat'],
    supported_targets: ['fqdn', 'dns'],
    required_customer_setup: ['declared_secondary_dns_targets', 'failover_policy_declaration'],
    evidence_required: ['probe_result', 'health_signal'],
    stop_conditions: ['max_events_reached', 'max_duration_elapsed', 'customer_cancel', 'tenant_kill_switch'],
    verdict_logic: 'Metadata marker documents declared failover nameservers; correlate with probe DNS health for declared zone.',
    probe_profile: { kind: 'dns_resolve', max_requests: 2, timeout_ms: 5000 },
    safety_constraints: { max_events: 3, max_duration_seconds: 60, max_concurrent_runs_per_target_group: 1 },
    default_expected_behavior: 'must_block_before_origin',
    probe_simulation_profile: 'external_blocked',
  }),
  safeCheck({
    check_id: 'dns.zone_transfer_exposure.safe',
    version: '1.0.0',
    name: 'Zone Transfer Exposure (Safe)',
    vector_family: 'dns',
    description: 'Safe AXFR exposure metadata where customer authorizes a single bounded lookup (no zone scraping).',
    required_agent_modes: ['heartbeat'],
    supported_targets: ['fqdn', 'dns'],
    required_customer_setup: ['declared_zone_for_axfr_check', 'customer_authorizes_axfr_probe'],
    evidence_required: ['probe_result'],
    stop_conditions: ['max_events_reached', 'max_duration_elapsed', 'customer_cancel', 'tenant_kill_switch'],
    verdict_logic: 'Single DNS metadata probe confirms AXFR is refused or restricted when unauthorized.',
    probe_profile: { kind: 'metadata_marker', max_requests: 1, timeout_ms: 5000, marker: 'astranull-safe-marker' },
    safety_constraints: { max_events: 3, max_duration_seconds: 60, max_concurrent_runs_per_target_group: 1 },
    default_expected_behavior: 'must_block_before_origin',
    probe_simulation_profile: 'external_blocked',
  }),
  safeCheck({
    check_id: 'l7.cache_busting.safe',
    version: '1.0.0',
    name: 'Cache Busting Readiness (Safe)',
    vector_family: 'l7',
    description: 'Small set of cache-busting markers via bounded HEAD probes (no origin-pressure scenario).',
    required_agent_modes: ['canary', 'heartbeat'],
    supported_targets: ['url', 'fqdn'],
    required_customer_setup: ['declared_cache_bust_path', 'cache_policy_expectation'],
    evidence_required: ['probe_result', 'agent_observation'],
    stop_conditions: ['max_events_reached', 'max_duration_elapsed', 'customer_cancel', 'tenant_kill_switch'],
    verdict_logic: 'Up to five labeled HEAD probes observe cache status headers without sustained origin load.',
    probe_profile: { kind: 'http_head', max_requests: 5, timeout_ms: 5000, marker: 'astranull-safe-marker' },
    safety_constraints: { max_events: 5, max_duration_seconds: 120, max_concurrent_runs_per_target_group: 1 },
    default_expected_behavior: 'must_block_before_origin',
    probe_simulation_profile: 'external_blocked',
  }),
  safeCheck({
    check_id: 'l7.expensive_endpoint.safe',
    version: '1.0.0',
    name: 'Expensive Endpoint (Safe)',
    vector_family: 'l7',
    description: 'Low-rate probe of customer-declared expensive endpoint (no endpoint guessing).',
    required_agent_modes: ['canary', 'heartbeat'],
    supported_targets: ['url', 'fqdn'],
    required_customer_setup: ['declared_expensive_endpoint_url', 'expected_rate_or_challenge_behavior'],
    evidence_required: ['probe_result', 'agent_observation'],
    stop_conditions: ['max_events_reached', 'max_duration_elapsed', 'customer_cancel', 'tenant_kill_switch'],
    verdict_logic: 'Single HEAD to declared URL observes latency/status for quota or challenge signals.',
    probe_profile: { kind: 'http_head', max_requests: 1, timeout_ms: 5000 },
    safety_constraints: { max_events: 3, max_duration_seconds: 90, max_concurrent_runs_per_target_group: 1 },
    default_expected_behavior: 'must_block_before_origin',
    probe_simulation_profile: 'external_blocked',
  }),
  safeCheck({
    check_id: 'l7.login_abuse_flow.safe',
    version: '1.0.0',
    name: 'Login / OTP / Signup Abuse-Sensitive Flow (Safe)',
    vector_family: 'l7',
    description: 'Benign marker flow on customer-declared auth endpoints with isolated synthetic identity intent.',
    required_agent_modes: ['canary', 'heartbeat'],
    supported_targets: ['url', 'fqdn'],
    required_customer_setup: ['declared_auth_endpoint', 'isolated_synthetic_test_identity', 'customer_approves_auth_probe'],
    evidence_required: ['probe_result', 'agent_observation'],
    stop_conditions: ['max_events_reached', 'max_duration_elapsed', 'customer_cancel', 'tenant_kill_switch'],
    verdict_logic: 'HEAD/metadata marker only — correlate rate-limit or challenge headers without credential stuffing.',
    probe_profile: { kind: 'metadata_marker', max_requests: 1, timeout_ms: 5000, marker: 'astranull-safe-marker' },
    safety_constraints: { max_events: 3, max_duration_seconds: 90, max_concurrent_runs_per_target_group: 1 },
    default_expected_behavior: 'must_block_before_origin',
    probe_simulation_profile: 'external_blocked',
  }),
  safeCheck({
    check_id: 'l7.password_reset.safe',
    version: '1.0.0',
    name: 'Password Reset Abuse-Sensitive Flow (Safe)',
    vector_family: 'l7',
    description: 'Benign metadata validation on customer-declared password-reset path (no account enumeration flood).',
    required_agent_modes: ['canary', 'heartbeat'],
    supported_targets: ['url', 'fqdn'],
    required_customer_setup: ['declared_password_reset_endpoint', 'isolated_synthetic_test_identity'],
    evidence_required: ['probe_result'],
    stop_conditions: ['max_events_reached', 'max_duration_elapsed', 'customer_cancel', 'tenant_kill_switch'],
    verdict_logic: 'Single safe probe observes throttle/challenge behavior on declared reset URL.',
    probe_profile: { kind: 'http_head', max_requests: 1, timeout_ms: 5000 },
    safety_constraints: { max_events: 3, max_duration_seconds: 90, max_concurrent_runs_per_target_group: 1 },
    default_expected_behavior: 'must_block_before_origin',
    probe_simulation_profile: 'external_blocked',
  }),
  safeCheck({
    check_id: 'l7.api_quota_exhaustion.safe',
    version: '1.0.0',
    name: 'API Quota Exhaustion Readiness (Safe)',
    vector_family: 'l7',
    description: 'Safe token/user quota visibility check — not a quota burn-down attack.',
    required_agent_modes: ['canary', 'heartbeat'],
    supported_targets: ['url', 'fqdn'],
    required_customer_setup: ['declared_api_endpoint', 'test_api_identity_or_key_scope'],
    evidence_required: ['probe_result', 'agent_observation'],
    stop_conditions: ['max_events_reached', 'max_duration_elapsed', 'customer_cancel', 'tenant_kill_switch'],
    verdict_logic: 'Up to five spaced HEAD probes read quota/rate-limit headers without exhausting customer quotas.',
    probe_profile: { kind: 'http_head', max_requests: 5, timeout_ms: 5000, marker: 'astranull-safe-marker' },
    safety_constraints: { max_events: 5, max_duration_seconds: 120, max_concurrent_runs_per_target_group: 1 },
    default_expected_behavior: 'must_block_before_origin',
    probe_simulation_profile: 'external_blocked',
  }),
  safeCheck({
    check_id: 'l7.graphql_complexity.safe',
    version: '1.0.0',
    name: 'GraphQL Complexity Readiness (Safe)',
    vector_family: 'l7',
    description: 'Low-complexity customer-provided GraphQL path metadata (no deep nested query execution).',
    required_agent_modes: ['canary', 'heartbeat'],
    supported_targets: ['url', 'fqdn'],
    required_customer_setup: ['declared_graphql_endpoint', 'customer_provided_safe_query_descriptor'],
    evidence_required: ['probe_result'],
    stop_conditions: ['max_events_reached', 'max_duration_elapsed', 'customer_cancel', 'tenant_kill_switch'],
    verdict_logic: 'Metadata marker documents declared GraphQL endpoint; edge should expose depth/complexity limits.',
    probe_profile: { kind: 'metadata_marker', max_requests: 1, timeout_ms: 5000, marker: 'astranull-safe-marker' },
    safety_constraints: { max_events: 3, max_duration_seconds: 90, max_concurrent_runs_per_target_group: 1 },
    default_expected_behavior: 'must_block_before_origin',
    probe_simulation_profile: 'external_blocked',
  }),
  safeCheck({
    check_id: 'l7.bot_challenge_marker.safe',
    version: '1.0.0',
    name: 'Bot / Challenge Marker (Safe)',
    vector_family: 'l7',
    description: 'Harmless labeled probe to observe bot management or challenge behavior.',
    required_agent_modes: ['canary', 'heartbeat'],
    supported_targets: ['url', 'fqdn'],
    required_customer_setup: ['declared_protected_url', 'bot_management_expectation'],
    evidence_required: ['probe_result', 'agent_observation'],
    stop_conditions: ['max_events_reached', 'max_duration_elapsed', 'customer_cancel', 'tenant_kill_switch'],
    verdict_logic: 'HEAD with harmless marker should trigger challenge or block when bot controls are active.',
    probe_profile: { kind: 'http_head', max_requests: 1, timeout_ms: 5000, marker: 'astranull-safe-marker' },
    safety_constraints: { max_events: 3, max_duration_seconds: 90, max_concurrent_runs_per_target_group: 1 },
    default_expected_behavior: 'must_block_before_origin',
    probe_simulation_profile: 'external_blocked',
  }),
  safeCheck({
    check_id: 'tls.slow_header_body_timeout.safe',
    version: '1.0.0',
    name: 'Slow Header/Body Timeout Readiness (Safe)',
    vector_family: 'tls',
    description: 'Tiny bounded timeout metadata for slow-client readiness — not a slowloris attack.',
    required_agent_modes: ['heartbeat'],
    supported_targets: ['url', 'fqdn'],
    required_customer_setup: ['tls_terminated_endpoint', 'declared_idle_or_slow_client_policy'],
    evidence_required: ['probe_result'],
    stop_conditions: ['max_events_reached', 'max_duration_elapsed', 'customer_cancel', 'tenant_kill_switch'],
    verdict_logic: 'Single HEAD within strict timeout collects edge timeout behavior metadata only.',
    probe_profile: { kind: 'http_head', max_requests: 1, timeout_ms: 5000 },
    safety_constraints: { max_events: 3, max_duration_seconds: 90, max_concurrent_runs_per_target_group: 1 },
    default_expected_behavior: 'must_block_before_origin',
    probe_simulation_profile: 'external_blocked',
  }),
  safeCheck({
    check_id: 'tls.idle_connection_timeout.safe',
    version: '1.0.0',
    name: 'Idle Connection Timeout Readiness (Safe)',
    vector_family: 'tls',
    description: 'Metadata for idle connection cleanup readiness (no connection hoarding).',
    required_agent_modes: ['heartbeat'],
    supported_targets: ['url', 'fqdn'],
    required_customer_setup: ['tls_terminated_endpoint', 'connection_idle_policy_declaration'],
    evidence_required: ['probe_result', 'health_signal'],
    stop_conditions: ['max_events_reached', 'max_duration_elapsed', 'customer_cancel', 'tenant_kill_switch'],
    verdict_logic: 'Metadata marker documents idle timeout intent; correlate with single connect/HEAD lifecycle.',
    probe_profile: { kind: 'tls_session', max_requests: 1, timeout_ms: 5000 },
    safety_constraints: { max_events: 3, max_duration_seconds: 90, max_concurrent_runs_per_target_group: 1 },
    default_expected_behavior: 'must_block_before_origin',
    probe_simulation_profile: 'external_blocked',
  }),
  safeCheck({
    check_id: 'protocol.http2_rapid_reset_readiness.safe',
    version: '1.0.0',
    name: 'HTTP/2 Rapid Reset Readiness (Safe)',
    vector_family: 'protocol',
    description: 'HTTP/2 rapid-reset class readiness via config/metadata only (no reset flood).',
    required_agent_modes: ['heartbeat'],
    supported_targets: ['url', 'fqdn'],
    required_customer_setup: ['http2_enabled_endpoint', 'rapid_reset_mitigation_declaration'],
    evidence_required: ['probe_result', 'health_signal'],
    stop_conditions: ['max_events_reached', 'max_duration_elapsed', 'customer_cancel', 'tenant_kill_switch'],
    verdict_logic: 'Bounded HEAD over TLS collects HTTP/2 readiness signals without generating reset storms.',
    probe_profile: { kind: 'http_head', max_requests: 1, timeout_ms: 5000 },
    safety_constraints: { max_events: 3, max_duration_seconds: 90, max_concurrent_runs_per_target_group: 1 },
    default_expected_behavior: 'must_block_before_origin',
    probe_simulation_profile: 'external_blocked',
  }),
  safeCheck({
    check_id: 'protocol.http2_stream_concurrency.safe',
    version: '1.0.0',
    name: 'HTTP/2 Stream Concurrency (Safe)',
    vector_family: 'protocol',
    description: 'Low-rate HTTP/2 settings/stream limit metadata (no stream exhaustion).',
    required_agent_modes: ['heartbeat'],
    supported_targets: ['url', 'fqdn'],
    required_customer_setup: ['http2_enabled_endpoint', 'stream_limit_policy_declaration'],
    evidence_required: ['probe_result'],
    stop_conditions: ['max_events_reached', 'max_duration_elapsed', 'customer_cancel', 'tenant_kill_switch'],
    verdict_logic: 'Metadata marker plus single HEAD documents advertised stream/concurrency controls.',
    probe_profile: { kind: 'http2_settings', max_requests: 1, timeout_ms: 5000 },
    safety_constraints: { max_events: 3, max_duration_seconds: 90, max_concurrent_runs_per_target_group: 1 },
    default_expected_behavior: 'must_block_before_origin',
    probe_simulation_profile: 'external_blocked',
  }),
  safeCheck({
    check_id: 'protocol.grpc_reflection_stream.safe',
    version: '1.0.0',
    name: 'gRPC Reflection / Stream Readiness (Safe)',
    vector_family: 'protocol',
    description: 'Safe gRPC reflection and stream control metadata (no stream pressure).',
    required_agent_modes: ['heartbeat'],
    supported_targets: ['url', 'fqdn'],
    required_customer_setup: ['declared_grpc_endpoint', 'grpc_reflection_policy_intent'],
    evidence_required: ['probe_result', 'health_signal'],
    stop_conditions: ['max_events_reached', 'max_duration_elapsed', 'customer_cancel', 'tenant_kill_switch'],
    verdict_logic: 'Metadata marker documents gRPC endpoint; reflection should be disabled or restricted when unintended.',
    probe_profile: { kind: 'metadata_marker', max_requests: 1, timeout_ms: 5000, marker: 'astranull-safe-marker' },
    safety_constraints: { max_events: 3, max_duration_seconds: 90, max_concurrent_runs_per_target_group: 1 },
    default_expected_behavior: 'must_block_before_origin',
    probe_simulation_profile: 'external_blocked',
  }),
  safeCheck({
    check_id: 'protocol.websocket_connection_controls.safe',
    version: '1.0.0',
    name: 'WebSocket Connection Controls (Safe)',
    vector_family: 'protocol',
    description: 'WebSocket upgrade and connection-limit readiness metadata (no connection hoarding).',
    required_agent_modes: ['canary', 'heartbeat'],
    supported_targets: ['url', 'fqdn'],
    required_customer_setup: ['declared_websocket_endpoint', 'connection_limit_expectation'],
    evidence_required: ['probe_result', 'agent_observation'],
    stop_conditions: ['max_events_reached', 'max_duration_elapsed', 'customer_cancel', 'tenant_kill_switch'],
    verdict_logic: 'Metadata marker documents WS endpoint; correlate upgrade policy without sustained open connections.',
    probe_profile: { kind: 'metadata_marker', max_requests: 1, timeout_ms: 5000, marker: 'astranull-safe-marker' },
    safety_constraints: { max_events: 3, max_duration_seconds: 90, max_concurrent_runs_per_target_group: 1 },
    default_expected_behavior: 'must_block_before_origin',
    probe_simulation_profile: 'external_blocked',
  }),
  socGated({
    check_id: 'l3.connection_table_exhaustion.request_only',
    version: '1.0.0',
    name: 'Connection Table Exhaustion (SOC Request Only)',
    vector_family: 'l3_l4',
    description: 'SOC-gated controlled connection-state scenario — not customer-runnable; governed dry-run adapter only.',
    required_agent_modes: ['heartbeat'],
    required_customer_setup: ['soc_authorization_pack', 'declared_target_group_scope', 'connection_limit_abort_criteria'],
    evidence_required: ['approval_artifact', 'provider_telemetry', 'soc_runbook_ack'],
    stop_conditions: ['soc_kill_switch', 'abort_criteria_met', 'provider_stop_signal', 'max_approved_duration'],
    safety_constraints: { customer_runnable: false },
    default_expected_behavior: 'soc_approval_required',
    probe_simulation_profile: 'none',
  }),
  socGated({
    check_id: 'high_scale.dns_high_query.request_only',
    version: '1.0.0',
    name: 'DNS High-Query Simulation (SOC Request Only)',
    vector_family: 'high_scale',
    description: 'SOC-gated authoritative DNS QPS simulation request marker — no customer probe execution.',
    required_agent_modes: ['heartbeat'],
    required_customer_setup: ['soc_authorization_pack', 'declared_dns_zone_scope', 'provider_approval_artifact'],
    evidence_required: ['approval_artifact', 'provider_telemetry', 'soc_runbook_ack'],
    stop_conditions: ['soc_kill_switch', 'abort_criteria_met', 'provider_stop_signal', 'max_approved_duration'],
    safety_constraints: { customer_runnable: false },
    default_expected_behavior: 'soc_approval_required',
    probe_simulation_profile: 'none',
  }),
  socGated({
    check_id: 'ops.runbook_contact_validation.request_only',
    version: '1.0.0',
    name: 'Runbook / Emergency Contact Validation (SOC Request Only)',
    vector_family: 'operations',
    description: 'SOC workflow marker to validate runbook version, owners, and emergency contact reachability.',
    required_agent_modes: ['heartbeat'],
    required_customer_setup: ['current_runbook_artifact', 'emergency_contact_roster', 'soc_authorization_pack'],
    evidence_required: ['approval_artifact', 'runbook_version_audit', 'contact_ack_evidence'],
    stop_conditions: ['soc_kill_switch', 'validation_complete', 'max_approved_duration'],
    safety_constraints: { customer_runnable: false },
    default_expected_behavior: 'soc_approval_required',
    probe_simulation_profile: 'none',
  }),
  socGated({
    check_id: 'ops.kill_switch_drill.request_only',
    version: '1.0.0',
    name: 'Kill Switch Drill (SOC Request Only)',
    vector_family: 'operations',
    description: 'SOC-gated kill-switch drill request marker with dry-run or live stop per authorization pack.',
    required_agent_modes: ['heartbeat'],
    required_customer_setup: ['soc_authorization_pack', 'kill_switch_runbook', 'declared_drill_scope'],
    evidence_required: ['approval_artifact', 'stop_event_audit', 'adapter_confirmation'],
    stop_conditions: ['soc_kill_switch', 'drill_complete', 'abort_criteria_met'],
    safety_constraints: { customer_runnable: false },
    default_expected_behavior: 'soc_approval_required',
    probe_simulation_profile: 'none',
  }),
  socGated({
    check_id: 'ops.provider_telemetry.request_only',
    version: '1.0.0',
    name: 'Provider Telemetry Validation (SOC Request Only)',
    vector_family: 'operations',
    description: 'SOC request marker to validate provider/scrubber telemetry hooks during governed scenarios.',
    required_agent_modes: ['heartbeat'],
    required_customer_setup: ['provider_approval_artifact', 'telemetry_endpoint_declaration', 'soc_authorization_pack'],
    evidence_required: ['provider_telemetry', 'approval_artifact', 'soc_runbook_ack'],
    stop_conditions: ['soc_kill_switch', 'telemetry_validated', 'max_approved_duration'],
    safety_constraints: { customer_runnable: false },
    default_expected_behavior: 'soc_approval_required',
    probe_simulation_profile: 'none',
  }),
  socGated({
    check_id: 'high_scale.multi_vector.request_only',
    version: '1.0.0',
    name: 'Multi-Vector Simulation (SOC Request Only)',
    vector_family: 'high_scale',
    description: 'SOC-gated multi-vector coordination request marker — runbook and provider coordination required.',
    required_agent_modes: ['heartbeat'],
    required_customer_setup: ['soc_authorization_pack', 'multi_vector_scope_declaration', 'provider_approval_artifact'],
    evidence_required: ['approval_artifact', 'provider_telemetry', 'soc_runbook_ack', 'coordination_audit'],
    stop_conditions: ['soc_kill_switch', 'abort_criteria_met', 'provider_stop_signal', 'max_approved_duration'],
    safety_constraints: { customer_runnable: false },
    default_expected_behavior: 'soc_approval_required',
    probe_simulation_profile: 'none',
  }),
  socGated({
    check_id: 'high_scale.degradation_recovery.request_only',
    version: '1.0.0',
    name: 'Degradation / Recovery Drill (SOC Request Only)',
    vector_family: 'high_scale',
    description: 'SOC-gated degradation and recovery drill request marker with explicit stop and reporting criteria.',
    required_agent_modes: ['heartbeat'],
    required_customer_setup: ['soc_authorization_pack', 'recovery_runbook', 'declared_degradation_objectives'],
    evidence_required: ['approval_artifact', 'health_signal', 'post_test_report', 'soc_runbook_ack'],
    stop_conditions: ['soc_kill_switch', 'recovery_confirmed', 'abort_criteria_met', 'max_approved_duration'],
    safety_constraints: { customer_runnable: false },
    default_expected_behavior: 'soc_approval_required',
    probe_simulation_profile: 'none',
  }),
  socGated({
    check_id: 'high_scale.volumetric.request_only',
    version: '1.0.0',
    name: 'Volumetric L3/L4 (SOC Request Only)',
    vector_family: 'high_scale',
    description: 'High-scale volumetric validation — customer may request; SOC must approve and execute via governed dry-run adapter only.',
    required_agent_modes: ['heartbeat'],
    required_customer_setup: ['soc_authorization_pack', 'declared_target_group_scope', 'provider_approval_artifact'],
    evidence_required: ['approval_artifact', 'provider_telemetry', 'soc_runbook_ack'],
    stop_conditions: ['soc_kill_switch', 'abort_criteria_met', 'provider_stop_signal', 'max_approved_duration'],
    safety_constraints: { customer_runnable: false },
    default_expected_behavior: 'soc_approval_required',
    probe_simulation_profile: 'none',
  }),
  socGated({
    check_id: 'waf.offensive_sqli.soc',
    version: '1.0.0',
    name: 'WAF SQLi Offensive Suite (SOC Only)',
    vector_family: 'waf',
    description: 'SOC-gated SQL injection offensive probe suite against declared WAF assets — not customer self-service.',
    required_agent_modes: ['canary', 'heartbeat'],
    required_customer_setup: ['waf_offensive_authorization_pack', 'declared_waf_asset', 'staging_isolation'],
    evidence_required: ['approval_artifact', 'agent_observation', 'soc_runbook_ack'],
    stop_conditions: ['soc_kill_switch', 'abort_criteria_met', 'max_approved_requests'],
    remediation_template: 'Submit a SOC-gated WAF offensive request with authorization pack and staging window.',
    safety_constraints: { customer_runnable: false, max_requests: 12 },
    default_expected_behavior: 'must_block_before_origin',
    probe_simulation_profile: 'none',
  }),
  socGated({
    check_id: 'waf.offensive_xss.soc',
    version: '1.0.0',
    name: 'WAF XSS Offensive Suite (SOC Only)',
    vector_family: 'waf',
    description: 'SOC-gated XSS offensive probe suite — customer request only; SOC executes.',
    required_agent_modes: ['canary', 'heartbeat'],
    required_customer_setup: ['waf_offensive_authorization_pack', 'declared_waf_asset', 'staging_isolation'],
    evidence_required: ['approval_artifact', 'agent_observation', 'soc_runbook_ack'],
    stop_conditions: ['soc_kill_switch', 'abort_criteria_met', 'max_approved_requests'],
    safety_constraints: { customer_runnable: false, max_requests: 12 },
    default_expected_behavior: 'must_block_before_origin',
    probe_simulation_profile: 'none',
  }),
  socGated({
    check_id: 'waf.offensive_rce.soc',
    version: '1.0.0',
    name: 'WAF RCE Offensive Suite (SOC Only)',
    vector_family: 'waf',
    description: 'SOC-gated RCE/command-execution offensive probe suite.',
    required_agent_modes: ['canary', 'heartbeat'],
    required_customer_setup: ['waf_offensive_authorization_pack', 'declared_waf_asset', 'staging_isolation'],
    evidence_required: ['approval_artifact', 'agent_observation', 'soc_runbook_ack'],
    stop_conditions: ['soc_kill_switch', 'abort_criteria_met', 'max_approved_requests'],
    safety_constraints: { customer_runnable: false, max_requests: 8 },
    default_expected_behavior: 'must_block_before_origin',
    probe_simulation_profile: 'none',
  }),
  socGated({
    check_id: 'waf.offensive_path_traversal.soc',
    version: '1.0.0',
    name: 'WAF Path Traversal Offensive Suite (SOC Only)',
    vector_family: 'waf',
    description: 'SOC-gated path traversal offensive probe suite.',
    required_agent_modes: ['canary', 'heartbeat'],
    required_customer_setup: ['waf_offensive_authorization_pack', 'declared_waf_asset', 'staging_isolation'],
    evidence_required: ['approval_artifact', 'agent_observation', 'soc_runbook_ack'],
    stop_conditions: ['soc_kill_switch', 'abort_criteria_met', 'max_approved_requests'],
    safety_constraints: { customer_runnable: false, max_requests: 10 },
    default_expected_behavior: 'must_block_before_origin',
    probe_simulation_profile: 'none',
  }),
  socGated({
    check_id: 'waf.offensive_command_injection.soc',
    version: '1.0.0',
    name: 'WAF Command Injection Offensive Suite (SOC Only)',
    vector_family: 'waf',
    description: 'SOC-gated OS command injection offensive probe suite.',
    required_agent_modes: ['canary', 'heartbeat'],
    required_customer_setup: ['waf_offensive_authorization_pack', 'declared_waf_asset', 'staging_isolation'],
    evidence_required: ['approval_artifact', 'agent_observation', 'soc_runbook_ack'],
    stop_conditions: ['soc_kill_switch', 'abort_criteria_met', 'max_approved_requests'],
    safety_constraints: { customer_runnable: false, max_requests: 8 },
    default_expected_behavior: 'must_block_before_origin',
    probe_simulation_profile: 'none',
  }),
  socGated({
    check_id: 'waf.offensive_ldap_injection.soc',
    version: '1.0.0',
    name: 'WAF LDAP Injection Offensive Suite (SOC Only)',
    vector_family: 'waf',
    description: 'SOC-gated LDAP injection offensive probe suite.',
    required_agent_modes: ['canary', 'heartbeat'],
    required_customer_setup: ['waf_offensive_authorization_pack', 'declared_waf_asset', 'staging_isolation'],
    evidence_required: ['approval_artifact', 'agent_observation', 'soc_runbook_ack'],
    stop_conditions: ['soc_kill_switch', 'abort_criteria_met', 'max_approved_requests'],
    safety_constraints: { customer_runnable: false, max_requests: 6 },
    default_expected_behavior: 'must_block_before_origin',
    probe_simulation_profile: 'none',
  }),
  socGated({
    check_id: 'waf.offensive_ssti.soc',
    version: '1.0.0',
    name: 'WAF SSTI Offensive Suite (SOC Only)',
    vector_family: 'waf',
    description: 'SOC-gated server-side template injection offensive probe suite.',
    required_agent_modes: ['canary', 'heartbeat'],
    required_customer_setup: ['waf_offensive_authorization_pack', 'declared_waf_asset', 'staging_isolation'],
    evidence_required: ['approval_artifact', 'agent_observation', 'soc_runbook_ack'],
    stop_conditions: ['soc_kill_switch', 'abort_criteria_met', 'max_approved_requests'],
    safety_constraints: { customer_runnable: false, max_requests: 6 },
    default_expected_behavior: 'must_block_before_origin',
    probe_simulation_profile: 'none',
  }),
  socGated({
    check_id: 'waf.offensive_combined.soc',
    version: '1.0.0',
    name: 'WAF Combined Offensive Bundle (SOC Only)',
    vector_family: 'waf',
    description: 'SOC-gated multi-vector offensive bundle for approved staging windows.',
    required_agent_modes: ['canary', 'heartbeat'],
    required_customer_setup: ['waf_offensive_authorization_pack', 'declared_waf_asset', 'staging_isolation'],
    evidence_required: ['approval_artifact', 'agent_observation', 'soc_runbook_ack'],
    stop_conditions: ['soc_kill_switch', 'abort_criteria_met', 'max_approved_requests'],
    safety_constraints: { customer_runnable: false, max_requests: 24 },
    default_expected_behavior: 'must_block_before_origin',
    probe_simulation_profile: 'none',
  }),
  socGated({
    check_id: 'high_scale.application.request_only',
    version: '1.0.0',
    name: 'Application-Layer High-Scale (SOC Request Only)',
    vector_family: 'high_scale',
    description: 'SOC-gated application-layer high-scale validation request marker only.',
    required_agent_modes: ['heartbeat'],
    required_customer_setup: ['soc_authorization_pack', 'declared_l7_scope', 'provider_approval_artifact'],
    evidence_required: ['approval_artifact', 'provider_telemetry', 'soc_runbook_ack'],
    stop_conditions: ['soc_kill_switch', 'abort_criteria_met', 'provider_stop_signal', 'max_approved_duration'],
    safety_constraints: { customer_runnable: false },
    default_expected_behavior: 'soc_approval_required',
    probe_simulation_profile: 'none',
  }),
];

export function getCheckById(checkId) {
  return CHECK_CATALOG.find((c) => c.check_id === checkId) ?? null;
}

export function isCustomerRunnable(check) {
  if (!check) return false;
  if (check.risk_class === 'soc_gated') return false;
  if (check.safety_constraints?.customer_runnable === false) return false;
  return true;
}

export function evaluateCheckPrerequisites(check, { onlineAgents = [] } = {}) {
  const missing = [];
  for (const prereq of check.prerequisites ?? []) {
    if (prereq.startsWith('agent_mode:')) {
      const mode = prereq.replace('agent_mode:', '');
      const has = onlineAgents.some((a) => (a.capabilities ?? []).includes(mode));
      if (!has) missing.push(prereq);
    }
  }
  return missing;
}
