{{- if .Values.bootstrapToken }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.bootstrapTokenSecretName }}
type: Opaque
stringData:
  {{ .Values.bootstrapTokenSecretKey }}: {{ .Values.bootstrapToken | quote }}
{{- end }}