import assert from 'node:assert/strict';
import { describe, it } from 'node:test';
import { WAF_VENDOR_SIGNATURES } from '../../src/lib/data/edgeSignatureData.mjs';
import {
  EDGE_SIGNATURE_CORPUS_VERSION,
  classifyEdgeByAddress,
  classifyEdgeByCnameChain,
  classifyEdgeFingerprint,
  classifyWafVendorsFromResponseEvidence,
} from '../../src/lib/edgeFingerprint.mjs';

function vendorMatch(result, vendor) {
  return result.matches.find((match) => match.vendor === vendor) ?? null;
}

describe('wafw00f response semantics', () => {
  it('combines multiple passive Cloudflare signals without returning raw cookie values', () => {
    const secret = 'cookie-secret-never-returned-42';
    const result = classifyWafVendorsFromResponseEvidence({
      headerEntries: [
        { name: 'server', value: 'cloudflare' },
        { name: 'cf-ray', value: '8a1b2c3d4e5f' },
      ],
      setCookieHeaders: [`__cfduid=${secret}; Path=/; Secure`],
    });
    const cloudflare = vendorMatch(result, 'cloudflare');
    assert.ok(cloudflare);
    assert.ok(cloudflare.confidence >= 0.85);
    assert.equal(cloudflare.matched_signals.filter((signal) => signal.tier === 'passive').length, 3);
    assert.equal(result.conflicting_vendor_signals, false);
    assert.ok(!JSON.stringify(result).includes(secret));
  });

  it('does not evaluate block-page leaves without explicit captured block evidence', () => {
    const evidence = { bodyText: 'This error was generated by ModSecurity' };
    assert.equal(vendorMatch(classifyWafVendorsFromResponseEvidence(evidence), 'modsecurity'), null);
    assert.ok(vendorMatch(
      classifyWafVendorsFromResponseEvidence({ ...evidence, blockResponse: true }),
      'modsecurity',
    ));
  });

  it('preserves the Azure Application Gateway two-content AND truth table', () => {
    const first = '<center>Microsoft-Azure-Application-Gateway/v2</center>';
    const second = '<h1>403 Forbidden</h1>';
    const cases = [
      { bodyText: `${first}${second}`, blockResponse: true, expected: true },
      { bodyText: first, blockResponse: true, expected: false },
      { bodyText: second, blockResponse: true, expected: false },
      { bodyText: `${first}${second}`, blockResponse: false, expected: false },
    ];
    for (const evidence of cases) {
      const match = vendorMatch(classifyWafVendorsFromResponseEvidence(evidence), 'applicationgateway');
      assert.equal(Boolean(match), evidence.expected, JSON.stringify(evidence));
    }
  });

  it('preserves the Kemp mixed passive/block three-signal AND truth table', () => {
    const complete = {
      headerEntries: [{ name: 'x-servedby', value: 'KEMP-LM' }],
      statusCode: 403,
      bodyText: '<title>403 Forbidden</title>',
      blockResponse: true,
    };
    const variants = [
      [complete, true],
      [{ ...complete, headerEntries: [] }, false],
      [{ ...complete, statusCode: 404 }, false],
      [{ ...complete, bodyText: '' }, false],
      [{ ...complete, blockResponse: false }, false],
    ];
    for (const [evidence, expected] of variants) {
      const result = classifyWafVendorsFromResponseEvidence(evidence);
      assert.equal(Boolean(vendorMatch(result, 'kemp')), expected, JSON.stringify(evidence));
    }
    assert.equal(vendorMatch(classifyWafVendorsFromResponseEvidence(complete), 'kemp').matched_signals.length, 3);
  });

  it('preserves sequential NOT guards as an all-required Alert Logic schema', () => {
    const fragments = [
      '<title>requested url cannot be found',
      'we are sorry, but the page you are looking for cannot be found',
      'back to previous page',
      'proceed to homepage',
      'reference id',
    ];
    const all = fragments.join(' | ');
    assert.ok(vendorMatch(
      classifyWafVendorsFromResponseEvidence({ bodyText: all, blockResponse: true }),
      'alertlogic',
    ));
    for (const missing of fragments) {
      const bodyText = fragments.filter((fragment) => fragment !== missing).join(' | ');
      assert.equal(vendorMatch(
        classifyWafVendorsFromResponseEvidence({ bodyText, blockResponse: true }),
        'alertlogic',
      ), null, `Alert Logic must require ${missing}`);
    }
    assert.equal(vendorMatch(
      classifyWafVendorsFromResponseEvidence({ bodyText: all, blockResponse: false }),
      'alertlogic',
    ), null, 'unavailable block leaves must not be promoted by NOT');
  });

  it('preserves helper alternatives as OR without flattening their response tier', () => {
    for (const bodyText of [
      'FortiGuard Intrusion Prevention',
      'blocked via //globalurl.fortinet.net policy',
    ]) {
      assert.ok(vendorMatch(
        classifyWafVendorsFromResponseEvidence({ bodyText, blockResponse: true }),
        'fortiguard',
      ));
    }
    assert.equal(vendorMatch(classifyWafVendorsFromResponseEvidence({
      bodyText: 'generic web filter response',
      blockResponse: true,
    }), 'fortiguard'), null);
    assert.equal(vendorMatch(classifyWafVendorsFromResponseEvidence({
      bodyText: 'FortiGuard Intrusion Prevention',
      blockResponse: false,
    }), 'fortiguard'), null);
  });

  it('ports the formerly omitted ThreatX compound plugin', () => {
    const complete = {
      headerEntries: [{ name: 'x-request-id', value: 'request-42' }],
      bodyText: 'Forbidden - ID: 0123456789abcdef0123456789abcdef',
      statusCode: 403,
      blockResponse: true,
    };
    assert.ok(vendorMatch(classifyWafVendorsFromResponseEvidence(complete), 'threatx'));
    assert.equal(vendorMatch(
      classifyWafVendorsFromResponseEvidence({ ...complete, statusCode: 406 }),
      'threatx',
    ), null);
  });

  it('ports the formerly omitted Reflected Networks four-signal AND plugin', () => {
    const imageMarker = WAF_VENDOR_SIGNATURES.reflected.signatures[0].pattern;
    const complete = {
      bodyText: `${imageMarker} content="Request is denied" <title>Forbidden</title>`,
      statusCode: 403,
      blockResponse: true,
    };
    assert.ok(vendorMatch(classifyWafVendorsFromResponseEvidence(complete), 'reflected'));
    assert.equal(vendorMatch(
      classifyWafVendorsFromResponseEvidence({
        ...complete,
        bodyText: `${imageMarker} content="Request is denied"`,
      }),
      'reflected',
    ), null);
  });

  it('uses exact case-sensitive HTTP reason semantics', () => {
    const exact = {
      statusCode: 200,
      statusReason: 'Condition Intercepted',
      blockResponse: true,
    };
    assert.ok(vendorMatch(classifyWafVendorsFromResponseEvidence(exact), 'denyall'));
    for (const statusReason of [
      'condition intercepted',
      'Condition Intercepted by policy',
      'prefix Condition Intercepted',
    ]) {
      assert.equal(vendorMatch(
        classifyWafVendorsFromResponseEvidence({ ...exact, statusReason }),
        'denyall',
      ), null);
    }
    assert.equal(vendorMatch(
      classifyWafVendorsFromResponseEvidence({ ...exact, statusCode: 403 }),
      'denyall',
    ), null);
  });

  it('matches bounded Set-Cookie syntax, including non-empty-value semantics', () => {
    assert.ok(vendorMatch(classifyWafVendorsFromResponseEvidence({
      setCookieHeaders: ['al_sess=private-value; Path=/'],
    }), 'airlock'));
    assert.equal(vendorMatch(classifyWafVendorsFromResponseEvidence({
      setCookieHeaders: ['not_al_sess=private-value; Path=/'],
    }), 'airlock'), null);

    assert.ok(vendorMatch(classifyWafVendorsFromResponseEvidence({
      setCookieHeaders: ['TS12345678=present'],
    }), 'f5bigipasm'));
    assert.equal(vendorMatch(classifyWafVendorsFromResponseEvidence({
      setCookieHeaders: ['TS12345678='],
    }), 'f5bigipasm'), null, 'an empty value must not satisfy =.+');
  });

  it('keeps name-only cookie evidence conservative but backward compatible', () => {
    assert.ok(vendorMatch(classifyWafVendorsFromResponseEvidence({
      cookieNames: ['__cfduid'],
    }), 'cloudflare'));
    assert.equal(vendorMatch(classifyWafVendorsFromResponseEvidence({
      cookieNames: ['TS12345678'],
    }), 'f5bigipasm'), null, 'name-only evidence cannot prove a non-empty value');
  });

  it('evaluates regex-shaped header names', () => {
    const result = classifyWafVendorsFromResponseEvidence({
      headerEntries: [{ name: 'x-protected-by', value: 'shieldon.io' }],
    });
    const shieldon = vendorMatch(result, 'shieldon');
    assert.ok(shieldon);
    assert.ok(shieldon.matched_signals.some((signal) => signal.header === '[Xx]-[Pp]rotected-[Bb]y'));
  });

  it('keeps independent vendor fingerprints as stacked layers and rejects unrelated evidence', () => {
    const stacked = classifyWafVendorsFromResponseEvidence({
      headerEntries: [
        { name: 'server', value: 'cloudflare' },
        { name: 'x-dis-request-id', value: 'abc123' },
      ],
    });
    assert.ok(vendorMatch(stacked, 'cloudflare'));
    assert.ok(vendorMatch(stacked, 'dosarrest'));
    assert.equal(stacked.conflicting_vendor_signals, false);
    assert.equal(stacked.stacked_vendor_signals, true);

    const unrelated = classifyWafVendorsFromResponseEvidence({
      headerEntries: [{ name: 'content-type', value: 'text/html' }],
      setCookieHeaders: ['prefer=plain'],
      bodyText: '<html><body>hello</body></html>',
      statusCode: 200,
    });
    assert.equal(unrelated.best, null);
    assert.deepEqual(unrelated.matches, []);
  });

  it('is deterministic for identical evidence', () => {
    const evidence = {
      headerEntries: [{ name: 'server', value: 'cloudflare' }],
      setCookieHeaders: ['__cfduid=present'],
    };
    assert.deepEqual(
      classifyWafVendorsFromResponseEvidence(evidence),
      classifyWafVendorsFromResponseEvidence(evidence),
    );
  });
});

describe('cdncheck address and CNAME semantics', () => {
  it('classifies IPv4 and IPv6 CDN ranges', () => {
    assert.deepEqual(classifyEdgeByAddress('108.138.5.5'), [
      { family: 'cdn', provider: 'cloudfront' },
      { family: 'cloud', provider: 'aws' },
    ]);
    assert.deepEqual(classifyEdgeByAddress('2a04:4e40::1'), [
      { family: 'cdn', provider: 'fastly' },
    ]);
  });

  it('gives IPv4-mapped IPv6 exact IPv4 parity', () => {
    const ipv4 = classifyEdgeByAddress('108.138.5.5');
    assert.deepEqual(classifyEdgeByAddress('::ffff:108.138.5.5'), ipv4);
    assert.deepEqual(classifyEdgeByAddress('::ffff:6c8a:505'), ipv4);
  });

  it('exposes overlapping CDN, WAF, and cloud address types independently', () => {
    assert.deepEqual(classifyEdgeByAddress('185.143.232.1'), [
      { family: 'cdn', provider: 'arvancloud' },
      { family: 'waf', provider: 'arvancloud' },
      { family: 'cloud', provider: 'arvancloud' },
    ]);
  });

  it('returns no address hit for invalid or documentation-only inputs', () => {
    assert.deepEqual(
      classifyEdgeByAddress(['198.51.100.10', '203.0.113.7', 'not-an-ip', '']),
      [],
    );
  });

  it('returns explicit upstream WAF type for CNAME-only Akamai and CloudFront', () => {
    assert.deepEqual(classifyEdgeByCnameChain('shop.akamaiedge.net'), [
      { provider: 'akamai', type: 'waf', suffix: 'akamaiedge.net', host: 'shop.akamaiedge.net' },
    ]);
    assert.deepEqual(classifyEdgeByCnameChain('assets.cloudfront.net'), [
      { provider: 'amazon', type: 'waf', suffix: 'cloudfront.net', host: 'assets.cloudfront.net' },
    ]);

    for (const [host, provider, cdnProvider] of [
      ['shop.akamaiedge.net', 'akamai', 'akamai'],
      ['assets.cloudfront.net', 'amazon', 'cloudfront'],
    ]) {
      const result = classifyEdgeFingerprint({ cnameChain: [host] });
      assert.equal(result.waf_present, true);
      assert.deepEqual(result.waf_providers, [provider]);
      assert.equal(result.cdn_detected, true);
      assert.deepEqual(result.cdn_providers, [cdnProvider]);
      assert.deepEqual(result.address_matches, []);
    }
  });

  it('preserves every typed provider for duplicate common suffixes', () => {
    assert.deepEqual(classifyEdgeByCnameChain('asset.edgesuite.net'), [
      { provider: 'akamai', type: 'waf', suffix: 'edgesuite.net', host: 'asset.edgesuite.net' },
      { provider: 'edgecast', type: 'waf', suffix: 'edgesuite.net', host: 'asset.edgesuite.net' },
    ]);
    const result = classifyEdgeFingerprint({ cnameChain: ['asset.edgesuite.net'] });
    assert.equal(result.waf_present, true);
    assert.deepEqual(result.waf_providers, ['akamai', 'edgecast']);
    assert.equal(result.cdn_detected, true);
    assert.deepEqual(result.cdn_providers, ['akamai', 'edgecast']);
  });

  it('requires a hostname boundary and ignores IP literals for CNAME matching', () => {
    assert.deepEqual(classifyEdgeByCnameChain('cloudfront.net.evil.example'), []);
    assert.deepEqual(classifyEdgeByCnameChain('notcloudfront.net'), []);
    assert.deepEqual(classifyEdgeByCnameChain('192.0.2.10'), []);
  });
});

describe('combined edge fingerprint', () => {
  it('combines independent vendor, CDN-address, and typed CNAME provenance', () => {
    const result = classifyEdgeFingerprint({
      headerEntries: [{ name: 'server', value: 'cloudflare' }],
      resolvedIps: ['108.138.5.5'],
      cnameChain: ['example.com.akamaiedge.net'],
    });
    assert.equal(result.corpus_version, EDGE_SIGNATURE_CORPUS_VERSION);
    assert.equal(result.metadata_only, true);
    assert.equal(result.waf_present, true);
    assert.deepEqual(result.waf_providers, ['akamai', 'cloudflare']);
    assert.equal(result.cdn_detected, true);
    // `server: cloudflare` is a proxied Cloudflare edge (curated header layer) as well as a WAF hit.
    // CNAME `example.com.akamaiedge.net` adds `akamai` CDN, and IP `108.138.5.5` adds `cloudfront`.
    assert.deepEqual(result.cdn_providers, ['akamai', 'cloudflare', 'cloudfront']);
    assert.equal(result.best_vendor.vendor, 'cloudflare');
    assert.deepEqual(result.address_matches, [
      { family: 'cdn', provider: 'cloudfront' },
      { family: 'cloud', provider: 'aws' },
    ]);
    assert.deepEqual(result.cloud_providers, ['aws']);
    assert.equal(result.cloud_hosted, true);
    assert.deepEqual(result.cname_matches, [
      { provider: 'akamai', type: 'waf', suffix: 'akamaiedge.net', host: 'example.com.akamaiedge.net' },
    ]);
  });

  it('preserves CDN and multiple WAF providers as evidence-backed layers', () => {
    const result = classifyEdgeFingerprint({
      headerEntries: [
        { name: 'server', value: 'cloudflare' },
        { name: 'x-amz-id', value: 'request-1' },
      ],
      resolvedIps: ['108.138.5.5'],
      cnameChain: ['edge.cloudflare.com'],
    });

    assert.deepEqual(result.waf_providers, ['awswaf', 'cloudflare']);
    assert.deepEqual(result.cdn_providers, ['cloudflare', 'cloudfront']);
    assert.equal(result.stacked_vendor_signals, true);
    assert.equal(result.conflicting_provider_signals, false);
    assert.deepEqual(
      result.layers.map((layer) => [layer.family, layer.provider]),
      [
        ['cdn', 'cloudflare'],
        ['cdn', 'cloudfront'],
        ['waf', 'cloudflare'],
        ['waf', 'awswaf'],
        ['cloud', 'aws'],
      ],
    );
    const cloudflare = result.layers.find((layer) => (
      layer.family === 'waf' && layer.provider === 'cloudflare'
    ));
    assert.deepEqual(cloudflare.sources, ['response_fingerprint', 'cname_suffix']);
    assert.equal(cloudflare.evidence_consistency, 'agreement');
    assert.ok(cloudflare.confidence > result.layers.find((layer) => layer.provider === 'awswaf').confidence);
    assert.equal(result.evidence_consistency, 'agreement');
  });

  it('boosts one layer only when header, IP-range, and CNAME evidence agree', () => {
    const result = classifyEdgeFingerprint({
      headerEntries: [{ name: 'server', value: 'cloudflare' }],
      resolvedIps: ['104.16.1.1'],
      cnameChain: ['edge.cloudflare.com'],
    });
    const layer = result.layers.find((entry) => (
      entry.family === 'waf' && entry.provider === 'cloudflare'
    ));
    assert.deepEqual(layer.sources, [
      'response_fingerprint',
      'address_range',
      'cname_suffix',
    ]);
    assert.equal(layer.evidence_consistency, 'agreement');
    assert.equal(layer.confidence, 0.9);
    assert.equal(result.confidence, 0.9);
  });

  it('discounts confidence when one CNAME suffix ambiguously maps to multiple providers', () => {
    const result = classifyEdgeFingerprint({ cnameChain: ['asset.edgesuite.net'] });
    assert.equal(result.conflicting_provider_signals, true);
    assert.equal(result.evidence_consistency, 'conflict');
    assert.ok(result.confidence < Math.max(...result.layers.map((layer) => layer.confidence)));
    assert.deepEqual(result.waf_providers, ['akamai', 'edgecast']);
  });

  it('does not promote an uncorroborated generic status heuristic to WAF presence', () => {
    const heuristic = classifyEdgeFingerprint({
      genericDetection: { found: true, reason_code: 'status_code_changed' },
      dnsObserved: true,
    });
    assert.equal(heuristic.waf_present, false);
    assert.equal(heuristic.waf_generic_detected, false);
    assert.equal(heuristic.wafw00f.detected, false);

    const corroborated = classifyEdgeFingerprint({
      genericDetection: {
        found: true,
        corroborated: true,
        reason_code: 'status_code_changed',
      },
      dnsObserved: true,
    });
    assert.equal(corroborated.waf_present, true);
    assert.equal(corroborated.waf_generic_detected, true);
    assert.equal(corroborated.layers[0].provider, 'generic');
  });

  it('reports neither WAF nor CDN on plain origin evidence', () => {
    const result = classifyEdgeFingerprint({
      headerEntries: [{ name: 'server', value: 'nginx/1.24.0' }],
      resolvedIps: ['198.51.100.10'],
      cnameChain: ['origin.internal.example.test'],
    });
    assert.equal(result.waf_present, false);
    assert.deepEqual(result.waf_providers, []);
    assert.equal(result.cdn_detected, false);
    assert.deepEqual(result.cdn_providers, []);
    assert.equal(result.best_vendor, null);
    assert.deepEqual(result.vendor_matches, []);
  });

  it('never reports a corpus WAF from an unmatched generic block response', () => {
    const result = classifyEdgeFingerprint({
      statusCode: 429,
      bodyText: 'totally-unique-nonmatching-text-xyzzy',
      blockResponse: true,
    });
    assert.equal(result.waf_present, false);
    assert.equal(result.best_vendor, null);
    assert.deepEqual(result.vendor_matches, []);
  });

  it('keeps WAF range membership independent of vendor signatures', () => {
    const result = classifyEdgeFingerprint({ resolvedIps: ['185.143.232.1'] });
    assert.equal(result.waf_present, true);
    assert.deepEqual(result.waf_providers, ['arvancloud']);
    assert.equal(result.cdn_detected, true);
    assert.deepEqual(result.cdn_providers, ['arvancloud']);
    assert.equal(result.best_vendor, null);
  });
});

describe('curated CDN / edge-platform header layers', async () => {
  const { classifyEdgeByResponseHeaders, classifyEdgeFingerprint: classify, extractFingerprintHeaderEntries } = await import('../../src/lib/edgeFingerprint.mjs');
  const headers = (pairs) => Object.entries(pairs).map(([name, value]) => ({ name, value }));

  it('identifies header-only edge platforms as CDN layers', () => {
    assert.deepEqual(
      classifyEdgeByResponseHeaders(headers({ server: 'Vercel', 'x-vercel-id': 'iad1::abc' })).map((m) => m.provider),
      ['vercel'],
    );
    assert.deepEqual(
      classifyEdgeByResponseHeaders(headers({ 'x-azure-ref': '0abc', via: '1.1 google' })).map((m) => m.provider),
      ['azure_front_door', 'google'],
    );
    const result = classify({ normal: { headerEntries: headers({ server: 'Netlify', 'x-nf-request-id': '01H' }), statusCode: 200 } });
    assert.equal(result.cdn_detected, true);
    assert.deepEqual(result.cdn_providers, ['netlify']);
    assert.equal(result.waf_present, false, 'a CDN header must never imply a WAF');
    assert.ok(result.layers.some((layer) => layer.family === 'cdn' && layer.sources.includes('response_header')));
  });

  it('does not match generic origin servers or look-alike values', () => {
    assert.deepEqual(classifyEdgeByResponseHeaders(headers({ server: 'nginx', via: '1.1 varnish' })), []);
    assert.deepEqual(classifyEdgeByResponseHeaders(headers({ server: 'cloudflare-nginx-clone' })), []);
    assert.deepEqual(classifyEdgeByResponseHeaders(headers({ 'cf-ray': 'not a ray id' })), []);
  });

  it('extracts curated header names from a real response for classification', () => {
    const response = { headers: new Headers({ 'x-amz-cf-id': 'abc==', server: 'CloudFront', 'x-unrelated': '1' }) };
    const entries = extractFingerprintHeaderEntries(response);
    assert.ok(entries.some((entry) => entry.name === 'x-amz-cf-id'));
    assert.deepEqual(classifyEdgeByResponseHeaders(entries).map((m) => m.provider), ['cloudfront']);
  });
});
