import assert from 'node:assert/strict';
import { describe, it } from 'node:test';
import { WAF_VENDOR_SIGNATURES } from '../../src/lib/data/edgeSignatureData.mjs';
import {
  EDGE_SIGNATURE_CORPUS_VERSION,
  classifyEdgeByAddress,
  classifyEdgeByCnameChain,
  classifyEdgeFingerprint,
  classifyWafVendorsFromResponseEvidence,
} from '../../src/lib/edgeFingerprint.mjs';

function vendorMatch(result, vendor) {
  return result.matches.find((match) => match.vendor === vendor) ?? null;
}

describe('wafw00f response semantics', () => {
  it('combines multiple passive Cloudflare signals without returning raw cookie values', () => {
    const secret = 'cookie-secret-never-returned-42';
    const result = classifyWafVendorsFromResponseEvidence({
      headerEntries: [
        { name: 'server', value: 'cloudflare' },
        { name: 'cf-ray', value: '8a1b2c3d4e5f' },
      ],
      setCookieHeaders: [`__cfduid=${secret}; Path=/; Secure`],
    });
    const cloudflare = vendorMatch(result, 'cloudflare');
    assert.ok(cloudflare);
    assert.ok(cloudflare.confidence >= 0.85);
    assert.equal(cloudflare.matched_signals.filter((signal) => signal.tier === 'passive').length, 3);
    assert.equal(result.conflicting_vendor_signals, false);
    assert.ok(!JSON.stringify(result).includes(secret));
  });

  it('does not evaluate block-page leaves without explicit captured block evidence', () => {
    const evidence = { bodyText: 'This error was generated by ModSecurity' };
    assert.equal(vendorMatch(classifyWafVendorsFromResponseEvidence(evidence), 'modsecurity'), null);
    assert.ok(vendorMatch(
      classifyWafVendorsFromResponseEvidence({ ...evidence, blockResponse: true }),
      'modsecurity',
    ));
  });

  it('preserves the Azure Application Gateway two-content AND truth table', () => {
    const first = '<center>Microsoft-Azure-Application-Gateway/v2</center>';
    const second = '<h1>403 Forbidden</h1>';
    const cases = [
      { bodyText: `${first}${second}`, blockResponse: true, expected: true },
      { bodyText: first, blockResponse: true, expected: false },
      { bodyText: second, blockResponse: true, expected: false },
      { bodyText: `${first}${second}`, blockResponse: false, expected: false },
    ];
    for (const evidence of cases) {
      const match = vendorMatch(classifyWafVendorsFromResponseEvidence(evidence), 'applicationgateway');
      assert.equal(Boolean(match), evidence.expected, JSON.stringify(evidence));
    }
  });

  it('preserves the Kemp mixed passive/block three-signal AND truth table', () => {
    const complete = {
      headerEntries: [{ name: 'x-servedby', value: 'KEMP-LM' }],
      statusCode: 403,
      bodyText: '<title>403 Forbidden</title>',
      blockResponse: true,
    };
    const variants = [
      [complete, true],
      [{ ...complete, headerEntries: [] }, false],
      [{ ...complete, statusCode: 404 }, false],
      [{ ...complete, bodyText: '' }, false],
      [{ ...complete, blockResponse: false }, false],
    ];
    for (const [evidence, expected] of variants) {
      const result = classifyWafVendorsFromResponseEvidence(evidence);
      assert.equal(Boolean(vendorMatch(result, 'kemp')), expected, JSON.stringify(evidence));
    }
    assert.equal(vendorMatch(classifyWafVendorsFromResponseEvidence(complete), 'kemp').matched_signals.length, 3);
  });

  it('preserves sequential NOT guards as an all-required Alert Logic schema', () => {
    const fragments = [
      '<title>requested url cannot be found',
      'we are sorry, but the page you are looking for cannot be found',
      'back to previous page',
      'proceed to homepage',
      'reference id',
    ];
    const all = fragments.join(' | ');
    assert.ok(vendorMatch(
      classifyWafVendorsFromResponseEvidence({ bodyText: all, blockResponse: true }),
      'alertlogic',
    ));
    for (const missing of fragments) {
      const bodyText = fragments.filter((fragment) => fragment !== missing).join(' | ');
      assert.equal(vendorMatch(
        classifyWafVendorsFromResponseEvidence({ bodyText, blockResponse: true }),
        'alertlogic',
      ), null, `Alert Logic must require ${missing}`);
    }
    assert.equal(vendorMatch(
      classifyWafVendorsFromResponseEvidence({ bodyText: all, blockResponse: false }),
      'alertlogic',
    ), null, 'unavailable block leaves must not be promoted by NOT');
  });

  it('preserves helper alternatives as OR without flattening their response tier', () => {
    for (const bodyText of [
      'FortiGuard Intrusion Prevention',
      'blocked via //globalurl.fortinet.net policy',
    ]) {
      assert.ok(vendorMatch(
        classifyWafVendorsFromResponseEvidence({ bodyText, blockResponse: true }),
        'fortiguard',
      ));
    }
    assert.equal(vendorMatch(classifyWafVendorsFromResponseEvidence({
      bodyText: 'generic web filter response',
      blockResponse: true,
    }), 'fortiguard'), null);
    assert.equal(vendorMatch(classifyWafVendorsFromResponseEvidence({
      bodyText: 'FortiGuard Intrusion Prevention',
      blockResponse: false,
    }), 'fortiguard'), null);
  });

  it('ports the formerly omitted ThreatX compound plugin', () => {
    const complete = {
      headerEntries: [{ name: 'x-request-id', value: 'request-42' }],
      bodyText: 'Forbidden - ID: 0123456789abcdef0123456789abcdef',
      statusCode: 403,
      blockResponse: true,
    };
    assert.ok(vendorMatch(classifyWafVendorsFromResponseEvidence(complete), 'threatx'));
    assert.equal(vendorMatch(
      classifyWafVendorsFromResponseEvidence({ ...complete, statusCode: 406 }),
      'threatx',
    ), null);
  });

  it('ports the formerly omitted Reflected Networks four-signal AND plugin', () => {
    const imageMarker = WAF_VENDOR_SIGNATURES.reflected.signatures[0].pattern;
    const complete = {
      bodyText: `${imageMarker} content="Request is denied" <title>Forbidden</title>`,
      statusCode: 403,
      blockResponse: true,
    };
    assert.ok(vendorMatch(classifyWafVendorsFromResponseEvidence(complete), 'reflected'));
    assert.equal(vendorMatch(
      classifyWafVendorsFromResponseEvidence({
        ...complete,
        bodyText: `${imageMarker} content="Request is denied"`,
      }),
      'reflected',
    ), null);
  });

  it('uses exact case-sensitive HTTP reason semantics', () => {
    const exact = {
      statusCode: 200,
      statusReason: 'Condition Intercepted',
      blockResponse: true,
    };
    assert.ok(vendorMatch(classifyWafVendorsFromResponseEvidence(exact), 'denyall'));
    for (const statusReason of [
      'condition intercepted',
      'Condition Intercepted by policy',
      'prefix Condition Intercepted',
    ]) {
      assert.equal(vendorMatch(
        classifyWafVendorsFromResponseEvidence({ ...exact, statusReason }),
        'denyall',
      ), null);
    }
    assert.equal(vendorMatch(
      classifyWafVendorsFromResponseEvidence({ ...exact, statusCode: 403 }),
      'denyall',
    ), null);
  });

  it('matches bounded Set-Cookie syntax, including non-empty-value semantics', () => {
    assert.ok(vendorMatch(classifyWafVendorsFromResponseEvidence({
      setCookieHeaders: ['al_sess=private-value; Path=/'],
    }), 'airlock'));
    assert.equal(vendorMatch(classifyWafVendorsFromResponseEvidence({
      setCookieHeaders: ['not_al_sess=private-value; Path=/'],
    }), 'airlock'), null);

    assert.ok(vendorMatch(classifyWafVendorsFromResponseEvidence({
      setCookieHeaders: ['TS12345678=present'],
    }), 'f5bigipasm'));
    assert.equal(vendorMatch(classifyWafVendorsFromResponseEvidence({
      setCookieHeaders: ['TS12345678='],
    }), 'f5bigipasm'), null, 'an empty value must not satisfy =.+');
  });

  it('keeps name-only cookie evidence conservative but backward compatible', () => {
    assert.ok(vendorMatch(classifyWafVendorsFromResponseEvidence({
      cookieNames: ['__cfduid'],
    }), 'cloudflare'));
    assert.equal(vendorMatch(classifyWafVendorsFromResponseEvidence({
      cookieNames: ['TS12345678'],
    }), 'f5bigipasm'), null, 'name-only evidence cannot prove a non-empty value');
  });

  it('evaluates regex-shaped header names', () => {
    const result = classifyWafVendorsFromResponseEvidence({
      headerEntries: [{ name: 'x-protected-by', value: 'shieldon.io' }],
    });
    const shieldon = vendorMatch(result, 'shieldon');
    assert.ok(shieldon);
    assert.ok(shieldon.matched_signals.some((signal) => signal.header === '[Xx]-[Pp]rotected-[Bb]y'));
  });

  it('flags conflicting independent vendor signals and rejects unrelated evidence', () => {
    const conflicting = classifyWafVendorsFromResponseEvidence({
      headerEntries: [
        { name: 'server', value: 'cloudflare' },
        { name: 'x-dis-request-id', value: 'abc123' },
      ],
    });
    assert.ok(vendorMatch(conflicting, 'cloudflare'));
    assert.ok(vendorMatch(conflicting, 'dosarrest'));
    assert.equal(conflicting.conflicting_vendor_signals, true);

    const unrelated = classifyWafVendorsFromResponseEvidence({
      headerEntries: [{ name: 'content-type', value: 'text/html' }],
      setCookieHeaders: ['prefer=plain'],
      bodyText: '<html><body>hello</body></html>',
      statusCode: 200,
    });
    assert.equal(unrelated.best, null);
    assert.deepEqual(unrelated.matches, []);
  });

  it('is deterministic for identical evidence', () => {
    const evidence = {
      headerEntries: [{ name: 'server', value: 'cloudflare' }],
      setCookieHeaders: ['__cfduid=present'],
    };
    assert.deepEqual(
      classifyWafVendorsFromResponseEvidence(evidence),
      classifyWafVendorsFromResponseEvidence(evidence),
    );
  });
});

describe('cdncheck address and CNAME semantics', () => {
  it('classifies IPv4 and IPv6 CDN ranges', () => {
    assert.deepEqual(classifyEdgeByAddress('108.138.5.5'), [
      { family: 'cdn', provider: 'cloudfront' },
    ]);
    assert.deepEqual(classifyEdgeByAddress('2a04:4e40::1'), [
      { family: 'cdn', provider: 'fastly' },
    ]);
  });

  it('gives IPv4-mapped IPv6 exact IPv4 parity', () => {
    const ipv4 = classifyEdgeByAddress('108.138.5.5');
    assert.deepEqual(classifyEdgeByAddress('::ffff:108.138.5.5'), ipv4);
    assert.deepEqual(classifyEdgeByAddress('::ffff:6c8a:505'), ipv4);
  });

  it('exposes overlapping CDN and WAF address types independently', () => {
    assert.deepEqual(classifyEdgeByAddress('185.143.232.1'), [
      { family: 'cdn', provider: 'arvancloud' },
      { family: 'waf', provider: 'arvancloud' },
    ]);
  });

  it('returns no address hit for invalid or documentation-only inputs', () => {
    assert.deepEqual(
      classifyEdgeByAddress(['198.51.100.10', '203.0.113.7', 'not-an-ip', '']),
      [],
    );
  });

  it('returns explicit upstream WAF type for CNAME-only Akamai and CloudFront', () => {
    assert.deepEqual(classifyEdgeByCnameChain('shop.akamaiedge.net'), [
      { provider: 'akamai', type: 'waf', suffix: 'akamaiedge.net' },
    ]);
    assert.deepEqual(classifyEdgeByCnameChain('assets.cloudfront.net'), [
      { provider: 'amazon', type: 'waf', suffix: 'cloudfront.net' },
    ]);

    for (const [host, provider] of [
      ['shop.akamaiedge.net', 'akamai'],
      ['assets.cloudfront.net', 'amazon'],
    ]) {
      const result = classifyEdgeFingerprint({ cnameChain: [host] });
      assert.equal(result.waf_present, true);
      assert.deepEqual(result.waf_providers, [provider]);
      assert.equal(result.cdn_detected, false);
      assert.deepEqual(result.cdn_providers, []);
      assert.deepEqual(result.address_matches, []);
    }
  });

  it('preserves every typed provider for duplicate common suffixes', () => {
    assert.deepEqual(classifyEdgeByCnameChain('asset.edgesuite.net'), [
      { provider: 'akamai', type: 'waf', suffix: 'edgesuite.net' },
      { provider: 'edgecast', type: 'waf', suffix: 'edgesuite.net' },
    ]);
    const result = classifyEdgeFingerprint({ cnameChain: ['asset.edgesuite.net'] });
    assert.equal(result.waf_present, true);
    assert.deepEqual(result.waf_providers, ['akamai', 'edgecast']);
    assert.equal(result.cdn_detected, false);
    assert.deepEqual(result.cdn_providers, []);
  });

  it('requires a hostname boundary and ignores IP literals for CNAME matching', () => {
    assert.deepEqual(classifyEdgeByCnameChain('cloudfront.net.evil.example'), []);
    assert.deepEqual(classifyEdgeByCnameChain('notcloudfront.net'), []);
    assert.deepEqual(classifyEdgeByCnameChain('192.0.2.10'), []);
  });
});

describe('combined edge fingerprint', () => {
  it('combines independent vendor, CDN-address, and typed CNAME provenance', () => {
    const result = classifyEdgeFingerprint({
      headerEntries: [{ name: 'server', value: 'cloudflare' }],
      resolvedIps: ['108.138.5.5'],
      cnameChain: ['example.com.akamaiedge.net'],
    });
    assert.equal(result.corpus_version, EDGE_SIGNATURE_CORPUS_VERSION);
    assert.equal(result.metadata_only, true);
    assert.equal(result.waf_present, true);
    assert.deepEqual(result.waf_providers, ['akamai', 'cloudflare']);
    assert.equal(result.cdn_detected, true);
    assert.deepEqual(result.cdn_providers, ['cloudfront']);
    assert.equal(result.best_vendor.vendor, 'cloudflare');
    assert.deepEqual(result.address_matches, [{ family: 'cdn', provider: 'cloudfront' }]);
    assert.deepEqual(result.cname_matches, [
      { provider: 'akamai', type: 'waf', suffix: 'akamaiedge.net' },
    ]);
  });

  it('reports neither WAF nor CDN on plain origin evidence', () => {
    const result = classifyEdgeFingerprint({
      headerEntries: [{ name: 'server', value: 'nginx/1.24.0' }],
      resolvedIps: ['198.51.100.10'],
      cnameChain: ['origin.internal.example.test'],
    });
    assert.equal(result.waf_present, false);
    assert.deepEqual(result.waf_providers, []);
    assert.equal(result.cdn_detected, false);
    assert.deepEqual(result.cdn_providers, []);
    assert.equal(result.best_vendor, null);
    assert.deepEqual(result.vendor_matches, []);
  });

  it('never reports a corpus WAF from an unmatched generic block response', () => {
    const result = classifyEdgeFingerprint({
      statusCode: 429,
      bodyText: 'totally-unique-nonmatching-text-xyzzy',
      blockResponse: true,
    });
    assert.equal(result.waf_present, false);
    assert.equal(result.best_vendor, null);
    assert.deepEqual(result.vendor_matches, []);
  });

  it('keeps WAF range membership independent of vendor signatures', () => {
    const result = classifyEdgeFingerprint({ resolvedIps: ['185.143.232.1'] });
    assert.equal(result.waf_present, true);
    assert.deepEqual(result.waf_providers, ['arvancloud']);
    assert.equal(result.cdn_detected, true);
    assert.deepEqual(result.cdn_providers, ['arvancloud']);
    assert.equal(result.best_vendor, null);
  });
});
